#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: AffiliateKeyModal

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass AffiliateKeyModal.AffiliateKeyModal_C
// SuperAlignedSize(0x0590) SuperUnalignedSize(0x0590) SuperAlignment(0x0008) SuperLastMemberEnd(0x0590)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0658) StructUnalignedSize(0x0658) StructAlignment(0x0008)
// 0x00C8 (0x0658 - 0x0590)
class UAffiliateKeyModal_C final : public UFortAffilateModal
{
public:
	UAffiliateKeyModal_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x0590(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation* SuccessAnim; // 0x0598(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation* Shake; // 0x05A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage* Check; // 0x05A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C* CloseButton; // 0x05B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCloseButton_C* CloseButton_Mobile; // 0x05B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock* None; // 0x05C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock* None_0; // 0x05C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock* ConnectionError; // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock* Description; // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonActionWidget* EditTextActionWidget; // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock* EntryError; // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock* ErrorPart2; // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C* LaunchWebsite; // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULightbox_C* Lightbox; // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage* McpWaitingSpinner; // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortSimpleWidgetAnimationsPanel* SimpleWidgetAnimationsPanel; // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock* Warning; // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool Found; // 0x0620(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool ConnectionTimeout; // 0x0621(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_622[0x6]; // 0x0622(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()> OnPopupClosed; // 0x0628(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool bSkipAutoPopulate; // 0x0638(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8 Pad_639[0x7]; // 0x0639(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()> OnSuccess; // 0x0640(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool bShakeAnimationIsPlaying; // 0x0650(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_651[0x3]; // 0x0651(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName ShakeAnimation; // 0x0654(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:

	// Function AffiliateKeyModal.AffiliateKeyModal_C.None
	// [BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Func_None_0();

	// Function AffiliateKeyModal.AffiliateKeyModal_C.SetupAffiliateField
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x10) | UObject::ProcessInternal(0x76106A4)
	void SetupAffiliateField(const class FString& AffilateName);

	// Function AffiliateKeyModal.AffiliateKeyModal_C.OnSet
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void OnSet(bool bSuccess);

	// Function AffiliateKeyModal.AffiliateKeyModal_C.OnCheckComplete
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(3) | ParamSize(0x18) | UObject::ProcessInternal(0x76106A4)
	void OnCheckComplete(bool bSuccess, bool bWasValidAffiliateName, const class FString& AffilateNameChecked);

	// Function AffiliateKeyModal.AffiliateKeyModal_C.ExecuteUbergraph_AffiliateKeyModal
	// [Final, UbergraphFunction, HasDefaults]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_AffiliateKeyModal(int32 EntryPoint);

	// Function AffiliateKeyModal.AffiliateKeyModal_C.BP_OnActivated
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void BP_OnActivated();

	// Function AffiliateKeyModal.AffiliateKeyModal_C.BndEvt__IconTextButton_C_0_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
	// [BlueprintEvent]
	// NumParams(1) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void BndEvt__IconTextButton_C_0_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button);

	// Function AffiliateKeyModal.AffiliateKeyModal_C.BndEvt__CloseButton_Mobile_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature
	// [BlueprintEvent]
	// NumParams(1) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void BndEvt__CloseButton_Mobile_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button);

	// Function AffiliateKeyModal.AffiliateKeyModal_C.BndEvt__CloseButton_K2Node_ComponentBoundEvent_21_CommonButtonClicked__DelegateSignature
	// [BlueprintEvent]
	// NumParams(1) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void BndEvt__CloseButton_K2Node_ComponentBoundEvent_21_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button);

	// Function AffiliateKeyModal.AffiliateKeyModal_C.BndEvt__AffiliateKey_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature
	// [HasOutParams, BlueprintEvent]
	// NumParams(1) | ParamSize(0x18) | UObject::ProcessInternal(0x76106A4)
	void BndEvt__AffiliateKey_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature(const class FText& Text);

	// Function AffiliateKeyModal.AffiliateKeyModal_C.BndEvt__AcceptButton_K2Node_ComponentBoundEvent_26_CommonButtonClicked__DelegateSignature
	// [BlueprintEvent]
	// NumParams(1) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void BndEvt__AcceptButton_K2Node_ComponentBoundEvent_26_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AffiliateKeyModal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AffiliateKeyModal_C")
	}
	static class UAffiliateKeyModal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAffiliateKeyModal_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAffiliateKeyModal_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
