#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: AndroidRuntimeSettings

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum AndroidRuntimeSettings.EAndroidScreenOrientation
// NumValues: 0x0009
enum class EEAndroidScreenOrientation : uint8
{
	Portrait = 0,
	ReversePortrait = 1,
	SensorPortrait = 2,
	Landscape = 3,
	ReverseLandscape = 4,
	SensorLandscape = 5,
	Sensor = 6,
	FullSensor = 7,
	EAndroidScreenOrientation_MAX = 8,
};

// Enum AndroidRuntimeSettings.EAndroidDepthBufferPreference
// NumValues: 0x0005
enum class EEAndroidDepthBufferPreference : uint8
{
	Default = 0,
	Bits16 = 16,
	Bits24 = 24,
	Bits32 = 32,
	EAndroidDepthBufferPreference_MAX = 33,
};

// Enum AndroidRuntimeSettings.EAndroidInstallLocation
// NumValues: 0x0004
enum class EEAndroidInstallLocation : uint8
{
	InternalOnly = 0,
	PreferExternal = 1,
	Auto = 2,
	EAndroidInstallLocation_MAX = 3,
};

// Enum AndroidRuntimeSettings.EOculusMobileDevice
// NumValues: 0x0003
enum class EEOculusMobileDevice : uint8
{
	Quest = 1,
	Quest2 = 2,
	EOculusMobileDevice_MAX = 3,
};

// Enum AndroidRuntimeSettings.EAndroidAudio
// NumValues: 0x0004
enum class EEAndroidAudio : uint8
{
	Default = 0,
	OGG = 1,
	ADPCM = 2,
	EAndroidAudio_MAX = 3,
};

// Enum AndroidRuntimeSettings.EAndroidGraphicsDebugger
// NumValues: 0x0004
enum class EEAndroidGraphicsDebugger : uint8
{
	None = 0,
	Mali = 1,
	Adreno = 2,
	EAndroidGraphicsDebugger_MAX = 3,
};

// ScriptStruct AndroidRuntimeSettings.GooglePlayLeaderboardMapping
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0020) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct FGooglePlayLeaderboardMapping final
{
public:
	FGooglePlayLeaderboardMapping() {}

	class FString Name; // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString LeaderboardId; // 0x0010(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FGooglePlayLeaderboardMapping;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// ScriptStruct AndroidRuntimeSettings.GooglePlayAchievementMapping
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0020) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct FGooglePlayAchievementMapping final
{
public:
	FGooglePlayAchievementMapping() {}

	class FString Name; // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString AchievementID; // 0x0010(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FGooglePlayAchievementMapping;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
