#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaCustomizationSlotButtonWrapper

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function AthenaCustomizationSlotButtonWrapper.AthenaCustomizationSlotButtonWrapper_C.ResetPopulateAnimVisual
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UAthenaCustomizationSlotButtonWrapper_C_ResetPopulateAnimVisual final
{
public:
	UAthenaCustomizationSlotButtonWrapper_C_ResetPopulateAnimVisual() {}

	float CallFunc_GetEndTime_ReturnValue; // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_4[0x4]; // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAthenaCustomizationSlotButtonWrapper_C_ResetPopulateAnimVisual;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function AthenaCustomizationSlotButtonWrapper.AthenaCustomizationSlotButtonWrapper_C.GetCustomizationSlotActiveState
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0001)
// 0x0004 (0x0004 - 0x0000)
struct UAthenaCustomizationSlotButtonWrapper_C_GetCustomizationSlotActiveState final
{
public:
	UAthenaCustomizationSlotButtonWrapper_C_GetCustomizationSlotActiveState() {}

	bool bCosmeticAvaialble; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool bActive; // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_GetCustomizationSlotActiveState_bOutAttachableCosmeticAvailable; // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_GetCustomizationSlotActiveState_bOutActive; // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAthenaCustomizationSlotButtonWrapper_C_GetCustomizationSlotActiveState;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function AthenaCustomizationSlotButtonWrapper.AthenaCustomizationSlotButtonWrapper_C.ExecuteUbergraph_AthenaCustomizationSlotButtonWrapper
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00A8) StructUnalignedSize(0x00A8) StructAlignment(0x0008)
// 0x00A8 (0x00A8 - 0x0000)
struct UAthenaCustomizationSlotButtonWrapper_C_ExecuteUbergraph_AthenaCustomizationSlotButtonWrapper final
{
public:
	UAthenaCustomizationSlotButtonWrapper_C_ExecuteUbergraph_AthenaCustomizationSlotButtonWrapper() {}

	int32 EntryPoint; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool Temp_bool_Variable; // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility Temp_byte_Variable; // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility None; // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_7[0x1]; // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortFrontEndContext* CallFunc_GetContext_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonLegacy* None_0; // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_CanShowLockerSlotType_ReturnValue; // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_19[0x7]; // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonLegacy* None_1; // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility K2Node_Select_Default; // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_29[0x7]; // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonLegacy* K2Node_ComponentBoundEvent_Button; // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue; // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer* None_2; // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAthenaCustomizationParams K2Node_MakeStruct_AthenaCustomizationParams; // 0x0048(0x0048)()
	int32 K2Node_CustomEvent_ButtonIndex; // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Add_IntInt_ReturnValue; // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_Multiply_IntFloat_ReturnValue; // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_9C[0x4]; // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* None_3; // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAthenaCustomizationSlotButtonWrapper_C_ExecuteUbergraph_AthenaCustomizationSlotButtonWrapper;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function AthenaCustomizationSlotButtonWrapper.AthenaCustomizationSlotButtonWrapper_C.BndEvt__SlotButton_K2Node_ComponentBoundEvent_47_CommonButtonClicked__DelegateSignature
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_47_CommonButtonClicked__DelegateSignature final
{
public:
	UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_47_CommonButtonClicked__DelegateSignature() {}

	class UCommonButtonLegacy* Button; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_47_CommonButtonClicked__DelegateSignature;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function AthenaCustomizationSlotButtonWrapper.AthenaCustomizationSlotButtonWrapper_C.BndEvt__SlotButton_K2Node_ComponentBoundEvent_13_CommonButtonClicked__DelegateSignature
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_13_CommonButtonClicked__DelegateSignature final
{
public:
	UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_13_CommonButtonClicked__DelegateSignature() {}

	class UCommonButtonLegacy* Button; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_13_CommonButtonClicked__DelegateSignature;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function AthenaCustomizationSlotButtonWrapper.AthenaCustomizationSlotButtonWrapper_C.BndEvt__SlotButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature final
{
public:
	UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature() {}

	class UCommonButtonLegacy* Button; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAthenaCustomizationSlotButtonWrapper_C_BndEvt__SlotButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function AthenaCustomizationSlotButtonWrapper.AthenaCustomizationSlotButtonWrapper_C.AnimPopulateInternal
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct UAthenaCustomizationSlotButtonWrapper_C_AnimPopulateInternal final
{
public:
	UAthenaCustomizationSlotButtonWrapper_C_AnimPopulateInternal() {}

	int32 ButtonIndex; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAthenaCustomizationSlotButtonWrapper_C_AnimPopulateInternal;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
