#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaMOTDSimpleNewsWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass AthenaMOTDSimpleNewsWidget.AthenaMOTDSimpleNewsWidget_C
// SuperAlignedSize(0x0430) SuperUnalignedSize(0x0430) SuperAlignment(0x0008) SuperLastMemberEnd(0x0430)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0488) StructUnalignedSize(0x0484) StructAlignment(0x0008)
// 0x0058 (0x0488 - 0x0430)
class UAthenaMOTDSimpleNewsWidget_C final : public UFortAthenaMOTDSimpleNewsWidget
{
public:
	UAthenaMOTDSimpleNewsWidget_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation* Intro; // 0x0438(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage* Backplate; // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage* GlowBackground; // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage* Image_Background; // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage* Image_Border; // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage* Image_ColorFade; // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox* SizeBoxButtonSize; // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct CoreUObject::FColor DarkDefaultColor; // 0x0470(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct CoreUObject::FColor LightDefaultColor; // 0x0474(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct CoreUObject::FColor PreviewDarkColor; // 0x0478(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool TestPreviewColors; // 0x047C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_47D[0x3]; // 0x047D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FColor PreviewLightColor; // 0x0480(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:

	// Function AthenaMOTDSimpleNewsWidget.AthenaMOTDSimpleNewsWidget_C.SetDynamicColors
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(2) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void SetDynamicColors(const struct CoreUObject::FColor& Dark, const struct CoreUObject::FColor& Light);

	// Function AthenaMOTDSimpleNewsWidget.AthenaMOTDSimpleNewsWidget_C.PreConstruct
	// [BlueprintCosmetic, Event, Public, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void PreConstruct(bool IsDesignTime_PreConstruct);

	// Function AthenaMOTDSimpleNewsWidget.AthenaMOTDSimpleNewsWidget_C.OnPopulateNews
	// [Event, Public, HasOutParams, BlueprintEvent]
	// NumParams(1) | ParamSize(0xD0) | UObject::ProcessInternal(0x76106A4)
	void OnPopulateNews(const struct FAthenaMOTDBase& NewsEntry_OnPopulateNews);

	// Function AthenaMOTDSimpleNewsWidget.AthenaMOTDSimpleNewsWidget_C.ExecuteUbergraph_AthenaMOTDSimpleNewsWidget
	// [Final, UbergraphFunction, HasDefaults]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_AthenaMOTDSimpleNewsWidget(int32 EntryPoint);

	// Function AthenaMOTDSimpleNewsWidget.AthenaMOTDSimpleNewsWidget_C.BP_OnActivated
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaMOTDSimpleNewsWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AthenaMOTDSimpleNewsWidget_C")
	}
	static class UAthenaMOTDSimpleNewsWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaMOTDSimpleNewsWidget_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAthenaMOTDSimpleNewsWidget_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
