
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaCustomizationSlotButton

#include "Basic.hpp"

#include "AthenaCustomizationSlotButton_classes.hpp"
#include "AthenaCustomizationSlotButton_parameters.hpp"


SDK_NAMESPACE_START

// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.OnUpdateExclusiveWarning
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool bShouldWarn_OnUpdateExclusiveWarning (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaCustomizationSlotButton_C::OnUpdateExclusiveWarning(bool bShouldWarn_OnUpdateExclusiveWarning)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "OnUpdateExclusiveWarning");

	Params::UAthenaCustomizationSlotButton_C_OnUpdateExclusiveWarning Parms{};

	Parms.bShouldWarn_OnUpdateExclusiveWarning = bShouldWarn_OnUpdateExclusiveWarning;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.OnCustomizationSlotActiveStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool bInAttachableCosmeticAvailable_OnCustomizationSlotActiveStateChanged (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool bInActive_OnCustomizationSlotActiveStateChanged (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaCustomizationSlotButton_C::OnCustomizationSlotActiveStateChanged(bool bInAttachableCosmeticAvailable_OnCustomizationSlotActiveStateChanged, bool bInActive_OnCustomizationSlotActiveStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "OnCustomizationSlotActiveStateChanged");

	Params::UAthenaCustomizationSlotButton_C_OnCustomizationSlotActiveStateChanged Parms{};

	Parms.bInAttachableCosmeticAvailable_OnCustomizationSlotActiveStateChanged = bInAttachableCosmeticAvailable_OnCustomizationSlotActiveStateChanged;
	Parms.bInActive_OnCustomizationSlotActiveStateChanged = bInActive_OnCustomizationSlotActiveStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.OnCardImageAndWidthChanged
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const TSoftObjectPtr<class UTexture2D>& Image_OnCardImageAndWidthChanged (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, UObjectWrapper, HasGetValueTypeHash)
// float Width_OnCardImageAndWidthChanged (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaCustomizationSlotButton_C::OnCardImageAndWidthChanged(const TSoftObjectPtr<class UTexture2D>& Image_OnCardImageAndWidthChanged, float Width_OnCardImageAndWidthChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "OnCardImageAndWidthChanged");

	Params::UAthenaCustomizationSlotButton_C_OnCardImageAndWidthChanged Parms{};

	Parms.Image_OnCardImageAndWidthChanged = Image_OnCardImageAndWidthChanged;
	Parms.Width_OnCardImageAndWidthChanged = Width_OnCardImageAndWidthChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.OnArchivedStatusUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool bArchived_OnArchivedStatusUpdated (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaCustomizationSlotButton_C::OnArchivedStatusUpdated(bool bArchived_OnArchivedStatusUpdated)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "OnArchivedStatusUpdated");

	Params::UAthenaCustomizationSlotButton_C_OnArchivedStatusUpdated Parms{};

	Parms.bArchived_OnArchivedStatusUpdated = bArchived_OnArchivedStatusUpdated;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.HandleWidthChanged
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float Width (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaCustomizationSlotButton_C::HandleWidthChanged(float Width)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "HandleWidthChanged");

	Params::UAthenaCustomizationSlotButton_C_HandleWidthChanged Parms{};

	Parms.Width = Width;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.HandleActiveStateChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool CosmeticAvailable (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool Active (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaCustomizationSlotButton_C::HandleActiveStateChanged(bool CosmeticAvailable, bool Active)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "HandleActiveStateChanged");

	Params::UAthenaCustomizationSlotButton_C_HandleActiveStateChanged Parms{};

	Parms.CosmeticAvailable = CosmeticAvailable;
	Parms.Active = Active;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.GetSlotDebugName
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString ReturnValue (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UAthenaCustomizationSlotButton_C::GetSlotDebugName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "GetSlotDebugName");

	Params::UAthenaCustomizationSlotButton_C_GetSlotDebugName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.ExecuteUbergraph_AthenaCustomizationSlotButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32 EntryPoint (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaCustomizationSlotButton_C::ExecuteUbergraph_AthenaCustomizationSlotButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "ExecuteUbergraph_AthenaCustomizationSlotButton");

	Params::UAthenaCustomizationSlotButton_C_ExecuteUbergraph_AthenaCustomizationSlotButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaCustomizationSlotButton.AthenaCustomizationSlotButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaCustomizationSlotButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaCustomizationSlotButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
