
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaStormSurgeIconWidget

#include "Basic.hpp"

#include "AthenaStormSurgeIconWidget_classes.hpp"
#include "AthenaStormSurgeIconWidget_parameters.hpp"


SDK_NAMESPACE_START

// Function AthenaStormSurgeIconWidget.AthenaStormSurgeIconWidget_C.Anim_dmgOFF
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaStormSurgeIconWidget_C::Anim_dmgOFF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaStormSurgeIconWidget_C", "Anim_dmgOFF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaStormSurgeIconWidget.AthenaStormSurgeIconWidget_C.Anim_dmgON
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaStormSurgeIconWidget_C::Anim_dmgON()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaStormSurgeIconWidget_C", "Anim_dmgON");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
