#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioMotorSim

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_classes.hpp"
#include "AudioMotorSim_structs.hpp"


SDK_NAMESPACE_START

// Class AudioMotorSim.AudioMotorSimOutput
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0000) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
class IAudioMotorSimOutput final
{
public:
	IAudioMotorSimOutput() {}

	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioMotorSimOutput")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AudioMotorSimOutput")
	}
	static class IAudioMotorSimOutput* GetDefaultObj()
	{
		return GetDefaultObjImpl<IAudioMotorSimOutput>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_IAudioMotorSimOutput;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class AudioMotorSim.AudioMotorSimComponent
// SuperAlignedSize(0x00A0) SuperUnalignedSize(0x00A0) SuperAlignment(0x0008) SuperLastMemberEnd(0x008F)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00A8) StructUnalignedSize(0x00A8) StructAlignment(0x0008)
// 0x0008 (0x00A8 - 0x00A0)
class UAudioMotorSimComponent : public UActorComponent
{
public:
	UAudioMotorSimComponent() {}

	uint8 Pad_A0[0x8]; // 0x00A0(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioMotorSimComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AudioMotorSimComponent")
	}
	static class UAudioMotorSimComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioMotorSimComponent>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAudioMotorSimComponent;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class AudioMotorSim.AudioMotorSim
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0000) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
class IAudioMotorSim final
{
public:
	IAudioMotorSim() {}

	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioMotorSim")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AudioMotorSim")
	}
	static class IAudioMotorSim* GetDefaultObj()
	{
		return GetDefaultObjImpl<IAudioMotorSim>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_IAudioMotorSim;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class AudioMotorSim.AudioMotorModelComponent
// SuperAlignedSize(0x00A0) SuperUnalignedSize(0x00A0) SuperAlignment(0x0008) SuperLastMemberEnd(0x008F)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0100) StructUnalignedSize(0x0100) StructAlignment(0x0008)
// 0x0060 (0x0100 - 0x00A0)
class UAudioMotorModelComponent final : public UActorComponent
{
public:
	UAudioMotorModelComponent() {}

	TArray<struct FMotorSimEntry> SimComponents; // 0x00A0(0x0010)(ZeroConstructor, Transient, NativeAccessSpecifierPublic)
	TArray<TScriptInterface<class IAudioMotorSimOutput>> AudioComponents; // 0x00B0(0x0010)(ZeroConstructor, Transient, UObjectWrapper, NativeAccessSpecifierPublic)
	uint8 Pad_C0[0x40]; // 0x00C0(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:

	// Function AudioMotorSim.AudioMotorModelComponent.AddMotorAudioComponent
	// [Final, Native, Public, BlueprintCallable]
	// NumParams(1) | ParamSize(0x10) | NativeExecOffset(0x4B531DC)
	void AddMotorAudioComponent(TScriptInterface<class IAudioMotorSimOutput> InComponent);

	// Function AudioMotorSim.AudioMotorModelComponent.AddMotorSimComponent
	// [Final, Native, Public, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x4B53040)
	void AddMotorSimComponent(TScriptInterface<class IAudioMotorSim> InComponent, const int32 SortOrder);

	// Function AudioMotorSim.AudioMotorModelComponent.RemoveMotorAudioComponent
	// [Final, Native, Public, BlueprintCallable]
	// NumParams(1) | ParamSize(0x10) | NativeExecOffset(0x4B53134)
	void RemoveMotorAudioComponent(TScriptInterface<class IAudioMotorSimOutput> InComponent);

	// Function AudioMotorSim.AudioMotorModelComponent.RemoveMotorSimComponent
	// [Final, Native, Public, BlueprintCallable]
	// NumParams(1) | ParamSize(0x10) | NativeExecOffset(0x4B52F98)
	void RemoveMotorSimComponent(TScriptInterface<class IAudioMotorSim> InComponent);

	// Function AudioMotorSim.AudioMotorModelComponent.Reset
	// [Native, Public, BlueprintCallable]
	// NumParams(0) | ParamSize(0x0) | NativeExecOffset(0x459E630)
	void Reset();

	// Function AudioMotorSim.AudioMotorModelComponent.StartOutput
	// [Native, Public, BlueprintCallable]
	// NumParams(0) | ParamSize(0x0) | NativeExecOffset(0x4B532A0)
	void StartOutput();

	// Function AudioMotorSim.AudioMotorModelComponent.StopOutput
	// [Native, Public, BlueprintCallable]
	// NumParams(0) | ParamSize(0x0) | NativeExecOffset(0x4B53284)
	void StopOutput();

	// Function AudioMotorSim.AudioMotorModelComponent.Update
	// [Native, Public, BlueprintCallable]
	// NumParams(1) | ParamSize(0x2C) | NativeExecOffset(0x4B532BC)
	void Update(const struct FAudioMotorSimInputContext& Input);


	// Function AudioMotorSim.AudioMotorModelComponent.GetCachedInputData
	// [Final, Native, Public, BlueprintCallable, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x2C) | NativeExecOffset(0x4B52F0C)
	struct FAudioMotorSimInputContext GetCachedInputData() const;

	// Function AudioMotorSim.AudioMotorModelComponent.GetGear
	// [Final, Native, Public, BlueprintCallable, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x4) | NativeExecOffset(0x4B52F60)
	int32 GetGear() const;

	// Function AudioMotorSim.AudioMotorModelComponent.GetRpm
	// [Final, Native, Public, BlueprintCallable, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x4) | NativeExecOffset(0x4B52F7C)
	float GetRpm() const;

	// Function AudioMotorSim.AudioMotorModelComponent.GetRuntimeInfo
	// [Final, Native, Public, BlueprintCallable, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x14) | NativeExecOffset(0x4B52F3C)
	struct FAudioMotorSimRuntimeContext GetRuntimeInfo() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioMotorModelComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AudioMotorModelComponent")
	}
	static class UAudioMotorModelComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioMotorModelComponent>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAudioMotorModelComponent;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
