#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioMixer

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum AudioMixer.EAudioDeviceChangedRole
// NumValues: 0x0006
enum class EEAudioDeviceChangedRole : uint8
{
	Invalid = 0,
	Console = 1,
	Multimedia = 2,
	Communications = 3,
	Count = 4,
	EAudioDeviceChangedRole_MAX = 5,
};

// Enum AudioMixer.EAudioDeviceChangedState
// NumValues: 0x0007
enum class EEAudioDeviceChangedState : uint8
{
	Invalid = 0,
	Active = 1,
	Disabled = 2,
	NotPresent = 3,
	Unplugged = 4,
	Count = 5,
	EAudioDeviceChangedState_MAX = 6,
};

// Enum AudioMixer.EAudioMixerChannelType
// NumValues: 0x0016
enum class EEAudioMixerChannelType : uint8
{
	FrontLeft = 0,
	FrontRight = 1,
	FrontCenter = 2,
	LowFrequency = 3,
	BackLeft = 4,
	BackRight = 5,
	FrontLeftOfCenter = 6,
	FrontRightOfCenter = 7,
	BackCenter = 8,
	SideLeft = 9,
	SideRight = 10,
	TopCenter = 11,
	TopFrontLeft = 12,
	TopFrontCenter = 13,
	TopFrontRight = 14,
	TopBackLeft = 15,
	TopBackCenter = 16,
	TopBackRight = 17,
	Unknown = 18,
	ChannelTypeCount = 19,
	DefaultChannel = 0,
	EAudioMixerChannelType_MAX = 20,
};

// Enum AudioMixer.EAudioMixerStreamDataFormatType
// NumValues: 0x0005
enum class EEAudioMixerStreamDataFormatType : uint8
{
	Unknown = 0,
	Float = 1,
	Int16 = 2,
	Unsupported = 3,
	EAudioMixerStreamDataFormatType_MAX = 4,
};

// Enum AudioMixer.ESwapAudioOutputDeviceResultState
// NumValues: 0x0004
enum class EESwapAudioOutputDeviceResultState : uint8
{
	Failure = 0,
	Success = 1,
	None = 2,
	ESwapAudioOutputDeviceResultState_MAX = 3,
};

// Enum AudioMixer.EMusicalNoteName
// NumValues: 0x000D
enum class EEMusicalNoteName : uint8
{
	C = 0,
	Db = 1,
	D = 2,
	Eb = 3,
	E = 4,
	F = 5,
	Gb = 6,
	G = 7,
	Ab = 8,
	A = 9,
	Bb = 10,
	B = 11,
	EMusicalNoteName_MAX = 12,
};

// Enum AudioMixer.ESubmixEffectDynamicsProcessorType
// NumValues: 0x0007
enum class EESubmixEffectDynamicsProcessorType : uint8
{
	Compressor = 0,
	Limiter = 1,
	Expander = 2,
	Gate = 3,
	UpwardsCompressor = 4,
	Count = 5,
	ESubmixEffectDynamicsProcessorType_MAX = 6,
};

// Enum AudioMixer.ESubmixEffectDynamicsPeakMode
// NumValues: 0x0005
enum class EESubmixEffectDynamicsPeakMode : uint8
{
	MeanSquared = 0,
	RootMeanSquared = 1,
	Peak = 2,
	Count = 3,
	ESubmixEffectDynamicsPeakMode_MAX = 4,
};

// Enum AudioMixer.ESubmixEffectDynamicsChannelLinkMode
// NumValues: 0x0005
enum class EESubmixEffectDynamicsChannelLinkMode : uint8
{
	Disabled = 0,
	Average = 1,
	Peak = 2,
	Count = 3,
	ESubmixEffectDynamicsChannelLinkMode_MAX = 4,
};

// Enum AudioMixer.ESubmixEffectDynamicsKeySource
// NumValues: 0x0005
enum class EESubmixEffectDynamicsKeySource : uint8
{
	Default = 0,
	AudioBus = 1,
	Submix = 2,
	Count = 3,
	ESubmixEffectDynamicsKeySource_MAX = 4,
};

// ScriptStruct AudioMixer.SubmixEffectReverbSettings
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0040) StructUnalignedSize(0x0040) StructAlignment(0x0004)
// 0x0040 (0x0040 - 0x0000)
struct FSubmixEffectReverbSettings final
{
public:
	FSubmixEffectReverbSettings() {}

	bool bBypassEarlyReflections; // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1[0x3]; // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float ReflectionsDelay; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float GainHF; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float ReflectionsGain; // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bBypassLateReflections; // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_11[0x3]; // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float LateDelay; // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float DecayTime; // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float Density; // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float Diffusion; // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float AirAbsorptionGainHF; // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float DecayHFRatio; // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float LateGain; // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float Gain; // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float WetLevel; // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float DryLevel; // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bBypass; // 0x003C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_3D[0x3]; // 0x003D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FSubmixEffectReverbSettings;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// ScriptStruct AudioMixer.SubmixEffectEQBand
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0004)
// 0x0010 (0x0010 - 0x0000)
struct FSubmixEffectEQBand final
{
public:
	FSubmixEffectEQBand() {}

	float Frequency; // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float Bandwidth; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float GainDb; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 bEnabled : 1; // 0x000C(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8 Pad_D[0x3]; // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FSubmixEffectEQBand;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// ScriptStruct AudioMixer.SubmixEffectSubmixEQSettings
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct FSubmixEffectSubmixEQSettings final
{
public:
	FSubmixEffectSubmixEQSettings() {}

	TArray<struct FSubmixEffectEQBand> EQBands; // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FSubmixEffectSubmixEQSettings;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// ScriptStruct AudioMixer.SwapAudioOutputResult
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0028) StructUnalignedSize(0x0028) StructAlignment(0x0008)
// 0x0028 (0x0028 - 0x0000)
struct FSwapAudioOutputResult final
{
public:
	FSwapAudioOutputResult() {}

	class FString CurrentDeviceId; // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString RequestedDeviceId; // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EESwapAudioOutputDeviceResultState Result; // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_21[0x7]; // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FSwapAudioOutputResult;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// ScriptStruct AudioMixer.SubmixEffectDynamicProcessorFilterSettings
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x000C) StructUnalignedSize(0x000C) StructAlignment(0x0004)
// 0x000C (0x000C - 0x0000)
struct FSubmixEffectDynamicProcessorFilterSettings final
{
public:
	FSubmixEffectDynamicProcessorFilterSettings() {}

	uint8 bEnabled : 1; // 0x0000(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8 Pad_1[0x3]; // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float Cutoff; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float GainDb; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FSubmixEffectDynamicProcessorFilterSettings;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// ScriptStruct AudioMixer.SubmixEffectDynamicsProcessorSettings
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0060) StructUnalignedSize(0x0060) StructAlignment(0x0008)
// 0x0060 (0x0060 - 0x0000)
struct FSubmixEffectDynamicsProcessorSettings final
{
public:
	FSubmixEffectDynamicsProcessorSettings() {}

	EESubmixEffectDynamicsProcessorType DynamicsProcessorType; // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EESubmixEffectDynamicsPeakMode PeakMode; // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EESubmixEffectDynamicsChannelLinkMode LinkMode; // 0x0002(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_3[0x1]; // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float InputGainDb; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float ThresholdDb; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float Ratio; // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float KneeBandwidthDb; // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float LookAheadMsec; // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float AttackTimeMsec; // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float ReleaseTimeMsec; // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EESubmixEffectDynamicsKeySource KeySource; // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_21[0x7]; // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioBus* ExternalAudioBus; // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USoundSubmix* ExternalSubmix; // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 bChannelLinked : 1; // 0x0038(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Deprecated, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8 bAnalogMode : 1; // 0x0038(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8 bBypass : 1; // 0x0038(0x0001)(BitIndex: 0x02, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8 bKeyAudition : 1; // 0x0038(0x0001)(BitIndex: 0x03, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8 Pad_39[0x3]; // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float KeyGainDb; // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float OutputGainDb; // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSubmixEffectDynamicProcessorFilterSettings KeyHighshelf; // 0x0044(0x000C)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	struct FSubmixEffectDynamicProcessorFilterSettings KeyLowshelf; // 0x0050(0x000C)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	uint8 Pad_5C[0x4]; // 0x005C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FSubmixEffectDynamicsProcessorSettings;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// ScriptStruct AudioMixer.AudioOutputDeviceInfo
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0048) StructUnalignedSize(0x0048) StructAlignment(0x0008)
// 0x0048 (0x0048 - 0x0000)
struct FAudioOutputDeviceInfo final
{
public:
	FAudioOutputDeviceInfo() {}

	class FString Name; // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString DeviceID; // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32 NumChannels; // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32 SampleRate; // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EEAudioMixerStreamDataFormatType Format; // 0x0028(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_29[0x7]; // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EEAudioMixerChannelType> OutputChannelArray; // 0x0030(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	uint8 bIsSystemDefault : 1; // 0x0040(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8 bIsCurrentDevice : 1; // 0x0040(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (BlueprintVisible, BlueprintReadOnly, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8 Pad_41[0x7]; // 0x0041(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_FAudioOutputDeviceInfo;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
