#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Melee_Blade_Real

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "PhysicsCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function B_Melee_Blade_Real.B_Melee_Blade_Real_C.ExecuteUbergraph_B_Melee_Blade_Real
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0228) StructUnalignedSize(0x0228) StructAlignment(0x0008)
// 0x0228 (0x0228 - 0x0000)
struct AB_Melee_Blade_Real_C_ExecuteUbergraph_B_Melee_Blade_Real final
{
public:
	AB_Melee_Blade_Real_C_ExecuteUbergraph_B_Melee_Blade_Real() {}

	int32 EntryPoint; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_4[0x4]; // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult K2Node_Event_HitResult; // 0x0008(0x00E0)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	EEPhysicalSurface K2Node_Event_ImpactPhysicalSurface; // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_E9[0x7]; // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemComponent* K2Node_Event_SpawnedPSC; // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_K2_GetComponentLocation_ReturnValue; // 0x00F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_BreakHitResult_bBlockingHit; // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_BreakHitResult_bInitialOverlap; // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_112[0x2]; // 0x0112(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float CallFunc_BreakHitResult_Time; // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_BreakHitResult_Distance; // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_11C[0x4]; // 0x011C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_BreakHitResult_Location; // 0x0120(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_BreakHitResult_ImpactPoint; // 0x0138(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_BreakHitResult_Normal; // 0x0150(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_BreakHitResult_ImpactNormal; // 0x0168(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat; // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor* CallFunc_BreakHitResult_HitActor; // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent; // 0x0190(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName CallFunc_BreakHitResult_HitBoneName; // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName CallFunc_BreakHitResult_BoneName; // 0x019C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_BreakHitResult_HitItem; // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_BreakHitResult_ElementIndex; // 0x01A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_BreakHitResult_FaceIndex; // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_1AC[0x4]; // 0x01AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_BreakHitResult_TraceStart; // 0x01B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_BreakHitResult_TraceEnd; // 0x01C8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_Subtract_VectorVector_ReturnValue; // 0x01E0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPawn* K2Node_DynamicCast_AsFort_Pawn; // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_201[0x7]; // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator CallFunc_Conv_VectorToRotator_ReturnValue; // 0x0208(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue; // 0x0220(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AB_Melee_Blade_Real_C_ExecuteUbergraph_B_Melee_Blade_Real;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function B_Melee_Blade_Real.B_Melee_Blade_Real_C.OnPlayImpactFX
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00F0) StructUnalignedSize(0x00F0) StructAlignment(0x0008)
// 0x00F0 (0x00F0 - 0x0000)
struct AB_Melee_Blade_Real_C_OnPlayImpactFX final
{
public:
	AB_Melee_Blade_Real_C_OnPlayImpactFX() {}

	struct FHitResult HitResult; // 0x0000(0x00E0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	EEPhysicalSurface ImpactPhysicalSurface; // 0x00E0(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_E1[0x7]; // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemComponent* SpawnedPSC; // 0x00E8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AB_Melee_Blade_Real_C_OnPlayImpactFX;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
