#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: BacchusTopBar

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass BacchusTopBar.BacchusTopBar_C
// SuperAlignedSize(0x0518) SuperUnalignedSize(0x0518) SuperAlignment(0x0008) SuperLastMemberEnd(0x0518)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0560) StructUnalignedSize(0x0560) StructAlignment(0x0008)
// 0x0048 (0x0560 - 0x0518)
class UBacchusTopBar_C final : public UAthenaTopBar
{
public:
	UBacchusTopBar_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x0518(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation* BacchusNavBarTabs_FadeOut; // 0x0520(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation* IntroTabLabel; // 0x0528(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UOverlay* Container; // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGameFeatureStatus_C* GameFeatureStatus_HighResTextureDownload; // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox* HorizontalBox_TopContent; // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox* MobileTabTitle; // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone* None; // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone* None_0; // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:

	// Function BacchusTopBar.BacchusTopBar_C.UpdateMTXButton
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void UpdateMTXButton();

	// Function BacchusTopBar.BacchusTopBar_C.SetBottomTabsVisibility
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void SetBottomTabsVisibility(EESlateVisibility InVisibility);

	// Function BacchusTopBar.BacchusTopBar_C.OnMobileTabLabelChanged
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnMobileTabLabelChanged();

	// Function BacchusTopBar.BacchusTopBar_C.ExecuteUbergraph_BacchusTopBar
	// [Final, UbergraphFunction]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_BacchusTopBar(int32 EntryPoint);

	// Function BacchusTopBar.BacchusTopBar_C.CustomEvent
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void CustomEvent();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BacchusTopBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"BacchusTopBar_C")
	}
	static class UBacchusTopBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBacchusTopBar_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusTopBar_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
