#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: BacchusQuickbarSecondary

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "BacchusDynamicQuickbar_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass BacchusQuickbarSecondary.BacchusQuickbarSecondary_C
// SuperAlignedSize(0x0358) SuperUnalignedSize(0x0355) SuperAlignment(0x0008) SuperLastMemberEnd(0x0355)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x03A0) StructUnalignedSize(0x039C) StructAlignment(0x0008)
// 0x0048 (0x03A0 - 0x0358)
class UBacchusQuickbarSecondary_C final : public UBacchusDynamicQuickbar_C
{
public:
	UBacchusQuickbarSecondary_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame_BacchusQuickbarSecondary_C; // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox* _Horizontal_Box__Camera_Mode_Content; // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInvalidationBox* QuickbarSecondaryInvalidationBox; // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBacchusQuickbarSlot_C* QuickbarSlotF1; // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBacchusQuickbarSlot_C* QuickbarSlotF2; // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBacchusQuickbarSlot_C* QuickbarSlotF3; // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBacchusQuickbarSlot_C* QuickbarSlotF4; // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBacchusQuickbarSlot_C* QuickbarSlotF5; // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32 CurrentBuildingSlot; // 0x0398(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:

	// Function BacchusQuickbarSecondary.BacchusQuickbarSecondary_C.AnimationFinished
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void AnimationFinished();

	// Function BacchusQuickbarSecondary.BacchusQuickbarSecondary_C.Construct
	// [BlueprintCosmetic, Event, Public, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Construct();

	// Function BacchusQuickbarSecondary.BacchusQuickbarSecondary_C.ExecuteUbergraph_BacchusQuickbarSecondary
	// [Final, UbergraphFunction, HasDefaults]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_BacchusQuickbarSecondary(int32 EntryPoint);

	// Function BacchusQuickbarSecondary.BacchusQuickbarSecondary_C.GetSpecificSlot
	// [Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(2) | ParamSize(0x10) | UObject::ProcessInternal(0x76106A4)
	class UFortQuickBarSlotBase* GetSpecificSlot(int32 SlotNumber);

	// Function BacchusQuickbarSecondary.BacchusQuickbarSecondary_C.Maximize
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Maximize();

	// Function BacchusQuickbarSecondary.BacchusQuickbarSecondary_C.Minimize
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Minimize();

	// Function BacchusQuickbarSecondary.BacchusQuickbarSecondary_C.OnQuickBarSlotFocusChanged_Bind
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(2) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void OnQuickBarSlotFocusChanged_Bind(EEFortQuickBars QuickbarIndex, int32 Slot_0);

	// Function BacchusQuickbarSecondary.BacchusQuickbarSecondary_C.UpdateQuickBarCaching
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void UpdateQuickBarCaching(bool Desire_Caching);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BacchusQuickbarSecondary_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"BacchusQuickbarSecondary_C")
	}
	static class UBacchusQuickbarSecondary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBacchusQuickbarSecondary_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusQuickbarSecondary_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
