#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: BacchusLockerTab

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "UMG_structs.hpp"
#include "CommonInput_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BacchusLockerTab.BacchusLockerTab_C.UpdatePresetButtonStyles
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0028) StructUnalignedSize(0x0021) StructAlignment(0x0008)
// 0x0028 (0x0028 - 0x0000)
struct UBacchusLockerTab_C_UpdatePresetButtonStyles final
{
public:
	UBacchusLockerTab_C_UpdatePresetButtonStyles() {}

	EECommonInputType InputPin; // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEHorizontalAlignment Temp_byte_Variable; // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEHorizontalAlignment None; // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEHorizontalAlignment None_0; // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEHorizontalAlignment None_1; // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EECommonInputType None_2; // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_6[0x2]; // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UIconTextButton_C* K2Node_DynamicCast_AsIcon_Text_Button; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEHorizontalAlignment K2Node_Select_Default; // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_12[0x6]; // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UIconTextButton_C* None_3; // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_4; // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_UpdatePresetButtonStyles;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.PlaySlotClickedAnimation
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UBacchusLockerTab_C_PlaySlotClickedAnimation final
{
public:
	UBacchusLockerTab_C_PlaySlotClickedAnimation() {}

	class UAthenaCustomizationSlotButton_C* SlotToPlayAnimOn; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_IsValid_ReturnValue; // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_9[0x7]; // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_PlaySlotClickedAnimation;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.PlaySlotAnimationAndCenterSlot
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UBacchusLockerTab_C_PlaySlotAnimationAndCenterSlot final
{
public:
	UBacchusLockerTab_C_PlaySlotAnimationAndCenterSlot() {}

	bool CallFunc_IsValid_ReturnValue; // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_1[0x7]; // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* CallFunc_PlayAnimationReverse_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_PlaySlotAnimationAndCenterSlot;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.PlayEquippedLockerMusic_STW
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0019) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct UBacchusLockerTab_C_PlayEquippedLockerMusic_STW final
{
public:
	UBacchusLockerTab_C_PlayEquippedLockerMusic_STW() {}

	class UFortMusicContext* CallFunc_GetContext_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESubGame CallFunc_GetSubGame_ReturnValue; // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_9[0x7]; // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaMusicPackItemDefinition* CallFunc_GetEquippedMusicPack_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_EqualEqual_ByteByte_ReturnValue; // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_PlayEquippedLockerMusic_STW;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.OnRefreshForNewLoadout
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0011) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UBacchusLockerTab_C_OnRefreshForNewLoadout final
{
public:
	UBacchusLockerTab_C_OnRefreshForNewLoadout() {}

	class FString LoadoutName_OnRefreshForNewLoadout; // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool bIsShuffleTile_OnRefreshForNewLoadout; // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_OnRefreshForNewLoadout;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.None
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UBacchusLockerTab_C_None final
{
public:
	UBacchusLockerTab_C_None() {}

	EECommonInputType bNewInputType; // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_None;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.OnBeginPickingCustomizationSlot
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UBacchusLockerTab_C_OnBeginPickingCustomizationSlot final
{
public:
	UBacchusLockerTab_C_OnBeginPickingCustomizationSlot() {}

	class UAthenaCustomizationSlotSelectorButton* SlotButton_OnBeginPickingCustomizationSlot; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_OnBeginPickingCustomizationSlot;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.ExecuteUbergraph_BacchusLockerTab
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x01A0) StructUnalignedSize(0x0199) StructAlignment(0x0008)
// 0x01A0 (0x01A0 - 0x0000)
struct UBacchusLockerTab_C_ExecuteUbergraph_BacchusLockerTab final
{
public:
	UBacchusLockerTab_C_ExecuteUbergraph_BacchusLockerTab() {}

	int32 EntryPoint; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool Temp_bool_Variable; // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_5[0x3]; // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility Temp_byte_Variable; // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility None; // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_0; // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility None_1; // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility None_2; // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_3; // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_16[0x2]; // 0x0016(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FText Temp_text_Variable; // 0x0018(0x0018)()
	class FText None_4; // 0x0030(0x0018)()
	class FText None_5; // 0x0048(0x0018)()
	class UAthenaCustomizationSlotSelectorButton* K2Node_Event_SlotButton; // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAthenaCustomizationSlotButton_C* K2Node_DynamicCast_AsAthena_Customization_Slot_Button; // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_71[0x7]; // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* None_6; // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer* None_7; // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAthenaCustomizationParams K2Node_MakeStruct_AthenaCustomizationParams; // 0x0088(0x0048)()
	struct FAthenaCustomizationParams None_8; // 0x00D0(0x0048)()
	bool CallFunc_ShouldDisplayNextRandomPresetName_ReturnValue; // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EECommonInputType K2Node_CustomEvent_bNewInputType; // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_9; // 0x011A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_11B[0x5]; // 0x011B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue; // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString K2Node_Event_LoadoutName; // 0x0128(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool K2Node_Event_bIsShuffleTile; // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility K2Node_Select_Default; // 0x0139(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_13A[0x6]; // 0x013A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText None_10; // 0x0140(0x0018)()
	bool CallFunc_BooleanAND_ReturnValue; // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_EqualEqual_StrStr_ReturnValue; // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility None_11; // 0x015A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_15B[0x5]; // 0x015B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText CallFunc_Conv_StringToText_ReturnValue; // 0x0160(0x0018)()
	class FText None_12; // 0x0178(0x0018)()
	class USoloButton_C* K2Node_DynamicCast_AsSolo_Button; // 0x0190(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_13; // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_ExecuteUbergraph_BacchusLockerTab;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.BeginPickingCustomization
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0078) StructUnalignedSize(0x0078) StructAlignment(0x0008)
// 0x0078 (0x0078 - 0x0000)
struct UBacchusLockerTab_C_BeginPickingCustomization final
{
public:
	UBacchusLockerTab_C_BeginPickingCustomization() {}

	class UCommonButtonLegacy* WidgetToReturnFocusTo; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAthenaCustomizationParams CustomizationParams; // 0x0008(0x0048)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UAthenaCustomizationSlotButton_C* SlotButton; // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_NotEqual_ObjectObject_ReturnValue; // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None; // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_BooleanAND_ReturnValue; // 0x005A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_0; // 0x005B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_GetCustomizationSlotActiveState_bOutAttachableCosmeticAvailable; // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_GetCustomizationSlotActiveState_bOutActive; // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_5E[0x2]; // 0x005E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaCustomizationSlotButton_C* K2Node_DynamicCast_AsAthena_Customization_Slot_Button; // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_69[0x7]; // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue; // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_BeginPickingCustomization;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BacchusLockerTab.BacchusLockerTab_C.AnimShowRandomDisclaimerEnabled
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0020) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct UBacchusLockerTab_C_AnimShowRandomDisclaimerEnabled final
{
public:
	UBacchusLockerTab_C_AnimShowRandomDisclaimerEnabled() {}

	bool Show; // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_IsVisible_ReturnValue; // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_2[0x2]; // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()> K2Node_CreateDelegate_OutputDelegate; // 0x0004(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer* None; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBacchusLockerTab_C_AnimShowRandomDisclaimerEnabled;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
