
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: BacchusLocalPlayerInfo

#include "Basic.hpp"

#include "BacchusLocalPlayerInfo_classes.hpp"
#include "BacchusLocalPlayerInfo_parameters.hpp"


SDK_NAMESPACE_START

// Function BacchusLocalPlayerInfo.BacchusLocalPlayerInfo_C.Add Extension Widget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget* New_Widget (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBacchusLocalPlayerInfo_C::Add_Extension_Widget(class UUserWidget* New_Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BacchusLocalPlayerInfo_C", "Add Extension Widget");

	Params::UBacchusLocalPlayerInfo_C_Add_Extension_Widget Parms{};

	*reinterpret_cast<void**>(&Parms.New_Widget) = reinterpret_cast<void*>(New_Widget);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BacchusLocalPlayerInfo.BacchusLocalPlayerInfo_C.AdjustExtensionSlot
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EESlateVisibility InVisibility (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBacchusLocalPlayerInfo_C::AdjustExtensionSlot(EESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BacchusLocalPlayerInfo_C", "AdjustExtensionSlot");

	Params::UBacchusLocalPlayerInfo_C_AdjustExtensionSlot Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BacchusLocalPlayerInfo.BacchusLocalPlayerInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBacchusLocalPlayerInfo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BacchusLocalPlayerInfo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BacchusLocalPlayerInfo.BacchusLocalPlayerInfo_C.ExecuteUbergraph_BacchusLocalPlayerInfo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32 EntryPoint (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBacchusLocalPlayerInfo_C::ExecuteUbergraph_BacchusLocalPlayerInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BacchusLocalPlayerInfo_C", "ExecuteUbergraph_BacchusLocalPlayerInfo");

	Params::UBacchusLocalPlayerInfo_C_ExecuteUbergraph_BacchusLocalPlayerInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BacchusLocalPlayerInfo.BacchusLocalPlayerInfo_C.On Local Player View Target Change
// (BlueprintCallable, BlueprintEvent)

void UBacchusLocalPlayerInfo_C::On_Local_Player_View_Target_Change()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BacchusLocalPlayerInfo_C", "On Local Player View Target Change");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BacchusLocalPlayerInfo.BacchusLocalPlayerInfo_C.On Player Name Change
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString& NewName (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBacchusLocalPlayerInfo_C::On_Player_Name_Change(const class FString& NewName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BacchusLocalPlayerInfo_C", "On Player Name Change");

	Params::UBacchusLocalPlayerInfo_C_On_Player_Name_Change Parms{};

	Parms.NewName = std::move(NewName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BacchusLocalPlayerInfo.BacchusLocalPlayerInfo_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBacchusLocalPlayerInfo_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BacchusLocalPlayerInfo_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BacchusLocalPlayerInfo.BacchusLocalPlayerInfo_C.OnLocalPlayerRevived
// (BlueprintCallable, BlueprintEvent)

void UBacchusLocalPlayerInfo_C::OnLocalPlayerRevived()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BacchusLocalPlayerInfo_C", "OnLocalPlayerRevived");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
