#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS21_BattlePassRewardPage

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "UMG_structs.hpp"
#include "CommonInput_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPS21_BattlePassRewardPage.BPS21_BattlePassRewardPage_C.ExecuteUbergraph_BPS21_BattlePassRewardPage
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0088) StructUnalignedSize(0x0082) StructAlignment(0x0008)
// 0x0088 (0x0088 - 0x0000)
struct UBPS21_BattlePassRewardPage_C_ExecuteUbergraph_BPS21_BattlePassRewardPage final
{
public:
	UBPS21_BattlePassRewardPage_C_ExecuteUbergraph_BPS21_BattlePassRewardPage() {}

	int32 EntryPoint; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool Temp_bool_Variable; // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility Temp_byte_Variable; // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility Param_None_0; // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool Param_None_1; // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPageNavigator_C* K2Node_CustomEvent_PageNavigator; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 K2Node_Event_PageNumber; // 0x0010(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_EqualEqual_IntInt_ReturnValue; // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EESlateVisibility K2Node_Select_Default; // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_16[0x2]; // 0x0016(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer* Param_None_2; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EECommonInputType K2Node_Event_InputType; // 0x0028(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_29[0x7]; // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText CallFunc_MakeLiteralText_ReturnValue; // 0x0030(0x0018)()
	bool CallFunc_EqualEqual_ByteByte_ReturnValue; // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_49[0x7]; // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText Param_None_3; // 0x0050(0x0018)()
	class FText Param_None_4; // 0x0068(0x0018)()
	EERewardPageType K2Node_Event_InRewardPageType; // 0x0080(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_SwitchEnum_CmpSuccess; // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBPS21_BattlePassRewardPage_C_ExecuteUbergraph_BPS21_BattlePassRewardPage;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BPS21_BattlePassRewardPage.BPS21_BattlePassRewardPage_C.OnInitForPageType
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UBPS21_BattlePassRewardPage_C_OnInitForPageType final
{
public:
	UBPS21_BattlePassRewardPage_C_OnInitForPageType() {}

	EERewardPageType InRewardPageType; // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBPS21_BattlePassRewardPage_C_OnInitForPageType;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BPS21_BattlePassRewardPage.BPS21_BattlePassRewardPage_C.OnInputMethodChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UBPS21_BattlePassRewardPage_C_OnInputMethodChanged final
{
public:
	UBPS21_BattlePassRewardPage_C_OnInputMethodChanged() {}

	EECommonInputType InputType; // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBPS21_BattlePassRewardPage_C_OnInputMethodChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BPS21_BattlePassRewardPage.BPS21_BattlePassRewardPage_C.OnPageChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct UBPS21_BattlePassRewardPage_C_OnPageChanged final
{
public:
	UBPS21_BattlePassRewardPage_C_OnPageChanged() {}

	int32 PageNumber; // 0x0000(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBPS21_BattlePassRewardPage_C_OnPageChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BPS21_BattlePassRewardPage.BPS21_BattlePassRewardPage_C.None
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UBPS21_BattlePassRewardPage_C_None final
{
public:
	UBPS21_BattlePassRewardPage_C_None() {}

	class UPageNavigator_C* PageNavigator_0; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBPS21_BattlePassRewardPage_C_None;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function BPS21_BattlePassRewardPage.BPS21_BattlePassRewardPage_C.SequenceEvent__ENTRYPOINTBPS21_BattlePassRewardPage
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UBPS21_BattlePassRewardPage_C_SequenceEvent__ENTRYPOINTBPS21_BattlePassRewardPage final
{
public:
	UBPS21_BattlePassRewardPage_C_SequenceEvent__ENTRYPOINTBPS21_BattlePassRewardPage() {}

	class UPageNavigator_C* PageNavigator_0; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UBPS21_BattlePassRewardPage_C_SequenceEvent__ENTRYPOINTBPS21_BattlePassRewardPage;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
