#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChatContainer

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass ChatContainer.ChatContainer_C
// SuperAlignedSize(0x0358) SuperUnalignedSize(0x0358) SuperAlignment(0x0008) SuperLastMemberEnd(0x0358)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x03E8) StructUnalignedSize(0x03E8) StructAlignment(0x0008)
// 0x0090 (0x03E8 - 0x0358)
class UChatContainer_C final : public UFortChatContainer
{
public:
	UChatContainer_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation* SizeAnimation; // 0x0360(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation* FadeAnimation; // 0x0368(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCommonBorder* ChatBorder; // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder* CommonBorderBackground; // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C* ConsoleChatShortcut; // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher* CursorModeSwitcher; // 0x0388(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox* HBox_Messages; // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox* HBox_Tabs; // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox* HudContentHBox; // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UKeybindWidget_C* KeybindWidget; // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox* SizeBox_ChatSize; // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox* SizeBox_ConsoleButtonSpaceProvider; // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher* Switcher_SendButton; // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock* Text_Disabled; // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EEUMGSequencePlayMode None; // 0x03D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CurrentlyUsingGamepad; // 0x03D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool AnimationClosing; // 0x03D2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_3D3[0x5]; // 0x03D3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase* WindowCloseSound; // 0x03D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase* WindowOpenSound; // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:

	// Function ChatContainer.ChatContainer_C.Tick
	// [BlueprintCosmetic, Event, Public, BlueprintEvent]
	// NumParams(2) | ParamSize(0x44) | UObject::ProcessInternal(0x76106A4)
	void Tick(const struct FGeometry& MyGeometry_Tick, float InDeltaTime_Tick);

	// Function ChatContainer.ChatContainer_C.SetChatBoxStyle
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void SetChatBoxStyle();

	// Function ChatContainer.ChatContainer_C.OnSizeAnimationComplete
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnSizeAnimationComplete();

	// Function ChatContainer.ChatContainer_C.OnSendButtonDisplayChanged
	// [Event, Protected, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void OnSendButtonDisplayChanged(bool bShowSendButton_OnSendButtonDisplayChanged);

	// Function ChatContainer.ChatContainer_C.OnKeyDown
	// [BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(3) | ParamSize(0x130) | UObject::ProcessInternal(0x76106A4)
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry_OnKeyDown, const struct FKeyEvent& InKeyEvent_OnKeyDown);

	// Function ChatContainer.ChatContainer_C.OnChatOpenChanged
	// [Event, Protected, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void OnChatOpenChanged(bool bShouldBeOpen_OnChatOpenChanged);

	// Function ChatContainer.ChatContainer_C.HandleCursorModeChanged
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(3) | ParamSize(0x10) | UObject::ProcessInternal(0x76106A4)
	void HandleCursorModeChanged(bool bEnabled, class FName ActionName, class UUserWidget* Widget);

	// Function ChatContainer.ChatContainer_C.HandleChatOpenChanged
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void HandleChatOpenChanged(bool bChatShouldBeOpen);

	// Function ChatContainer.ChatContainer_C.FocusChat
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void FocusChat();

	// Function ChatContainer.ChatContainer_C.ExecuteUbergraph_ChatContainer
	// [Final, UbergraphFunction, HasDefaults]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_ChatContainer(int32 EntryPoint);

	// Function ChatContainer.ChatContainer_C.Destruct
	// [BlueprintCosmetic, Event, Public, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Destruct();

	// Function ChatContainer.ChatContainer_C.Construct
	// [BlueprintCosmetic, Event, Public, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Construct();

	// Function ChatContainer.ChatContainer_C.BndEvt__ConsoleChatShortcut_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
	// [BlueprintEvent]
	// NumParams(1) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void BndEvt__ConsoleChatShortcut_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button);

	// Function ChatContainer.ChatContainer_C.BndEvt__ChatContainer_ChatList_Messages_K2Node_ComponentBoundEvent_1_OnListEntryGeneratedDynamic__DelegateSignature
	// [BlueprintEvent]
	// NumParams(1) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void BndEvt__ChatContainer_ChatList_Messages_K2Node_ComponentBoundEvent_1_OnListEntryGeneratedDynamic__DelegateSignature(class UUserWidget* Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChatContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"ChatContainer_C")
	}
	static class UChatContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChatContainer_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UChatContainer_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
