#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: Curie

#include "Basic.hpp"

#include "ModularGameplay_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "Curie_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class Curie.CurieManagerComponent
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0030) StructUnalignedSize(0x0030) StructAlignment(0x0008)
// 0x0008 (0x0030 - 0x0028)
class UCurieManagerComponent : public UObject
{
public:
	UCurieManagerComponent() {}

	class UCurieManagerComponentConfig* CachedConfig; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieManagerComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieManagerComponent")
	}
	static class UCurieManagerComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieManagerComponent>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieManagerComponent;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieManagerComponentConfig
// SuperAlignedSize(0x0030) SuperUnalignedSize(0x0030) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0040) StructUnalignedSize(0x0040) StructAlignment(0x0008)
// 0x0010 (0x0040 - 0x0030)
class UCurieManagerComponentConfig : public UPrimaryDataAsset
{
public:
	UCurieManagerComponentConfig() {}

	uint8 Pad_30[0x8]; // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class FName ConfigName; // 0x0038(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTag ConfigTag; // 0x003C(0x0004)(Edit, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieManagerComponentConfig")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieManagerComponentConfig")
	}
	static class UCurieManagerComponentConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieManagerComponentConfig>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieManagerComponentConfig;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieManagerComponentInterface
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0000) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
class ICurieManagerComponentInterface final
{
public:
	ICurieManagerComponentInterface() {}

	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieManagerComponentInterface")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieManagerComponentInterface")
	}
	static class ICurieManagerComponentInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<ICurieManagerComponentInterface>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ICurieManagerComponentInterface;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieManager
// SuperAlignedSize(0x00A0) SuperUnalignedSize(0x00A0) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0630) StructUnalignedSize(0x0630) StructAlignment(0x0008)
// 0x0590 (0x0630 - 0x00A0)
class UCurieManager : public UGameStateComponent
{
public:
	UCurieManager() {}

	TSubclassOf<class UCurieComponent> CurieComponentClass; // 0x00A0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FName CurieManagerRegistryName; // 0x00A8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FName MaterialDataRegistryName; // 0x00AC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FName ElementDataRegistryName; // 0x00B0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FName EntityStateDataRegistryName; // 0x00B4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8 Pad_B8[0x298]; // 0x00B8(0x0298)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<struct FGameplayTag, class UCurieElementAllocationHandler*> ElementAllocationHandlers; // 0x0350(0x0050)(Transient, UObjectWrapper, NativeAccessSpecifierPrivate)
	TMap<struct FGameplayTag, struct FCurieElementAttachHandlersContainer> ElementAttachmentHandlers; // 0x03A0(0x0050)(Transient, NativeAccessSpecifierPrivate)
	TMap<struct FGameplayTag, struct FCurieElementAttachConditionHandlersContainer> ElementAttachmentConditionHandlers; // 0x03F0(0x0050)(Transient, NativeAccessSpecifierPrivate)
	TMap<struct FCurieElementPairKey, struct FCurieElementInteractWithElementHandlersContainer> ElementInteractWithElementHandlers; // 0x0440(0x0050)(Transient, NativeAccessSpecifierPrivate)
	TMap<struct FGameplayTag, struct FCurieElementInteractWithMaterialHandlersContainer> ElementInteractWithMaterialHandlers; // 0x0490(0x0050)(Transient, NativeAccessSpecifierPrivate)
	TMap<struct FGameplayTag, struct FCurieElementInteractWithContainerHandlersContainer> ElementInteractWithContainerHandlers; // 0x04E0(0x0050)(Transient, NativeAccessSpecifierPrivate)
	TArray<class UCurieManagerComponent*> CurieManagerComponents; // 0x0530(0x0010)(ZeroConstructor, Transient, NativeAccessSpecifierPrivate)
	uint8 Pad_540[0xF0]; // 0x0540(0x00F0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:

	// Function Curie.CurieManager.BindDelegateForCurieElementAttached
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x362583C)
	void BindDelegateForCurieElementAttached(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.BindDelegateForCurieElementBeginInteract
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x36251F4)
	void BindDelegateForCurieElementBeginInteract(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.BindDelegateForCurieElementDetached
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3625624)
	void BindDelegateForCurieElementDetached(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.BindDelegateForCurieElementEndInteract
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3624FDC)
	void BindDelegateForCurieElementEndInteract(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.BindDelegateForCurieElementInteract
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x362540C)
	void BindDelegateForCurieElementInteract(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.BindDelegateForCurieStateAttached
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3625C6C)
	void BindDelegateForCurieStateAttached(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& StateIdentifier)>& Delegate);

	// Function Curie.CurieManager.BindDelegateForCurieStateDetached
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3625A54)
	void BindDelegateForCurieStateDetached(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& StateIdentifier)>& Delegate);

	// Function Curie.CurieManager.HandleContainerOwnerDestroyed
	// [Final, Native, Private]
	// NumParams(1) | ParamSize(0x8) | NativeExecOffset(0x3624E28)
	void HandleContainerOwnerDestroyed(class AActor* OwnerActor);

	// Function Curie.CurieManager.UnbindDelegateForCurieElementAttached
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3625730)
	void UnbindDelegateForCurieElementAttached(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.UnbindDelegateForCurieElementBeginInteract
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x36250E8)
	void UnbindDelegateForCurieElementBeginInteract(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.UnbindDelegateForCurieElementDetached
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3625518)
	void UnbindDelegateForCurieElementDetached(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.UnbindDelegateForCurieElementEndInteract
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3624ED0)
	void UnbindDelegateForCurieElementEndInteract(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.UnbindDelegateForCurieElementInteract
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3625300)
	void UnbindDelegateForCurieElementInteract(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)>& Delegate);

	// Function Curie.CurieManager.UnbindDelegateForCurieStateAttached
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3625B60)
	void UnbindDelegateForCurieStateAttached(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& StateIdentifier)>& Delegate);

	// Function Curie.CurieManager.UnbindDelegateForCurieStateDetached
	// [Final, Native, Public, HasOutParams, BlueprintCallable]
	// NumParams(2) | ParamSize(0x14) | NativeExecOffset(0x3625948)
	void UnbindDelegateForCurieStateDetached(class UObject* CurieOwner, const TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& StateIdentifier)>& Delegate);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieManager")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieManager")
	}
	static class UCurieManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieManager>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieManager;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieInterface
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0000) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
class ICurieInterface final
{
public:
	ICurieInterface() {}


	// Function Curie.CurieInterface.OnCurieContainerAcquired_BP
	// [Event, Public, BlueprintEvent]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void OnCurieContainerAcquired_BP(const struct FCurieContainerHandle& CurieContainerHandle);

	// Function Curie.CurieInterface.OnCurieContainerReleased_BP
	// [Event, Public, BlueprintEvent]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void OnCurieContainerReleased_BP(const struct FCurieContainerHandle& CurieContainerHandle);

	// Function Curie.CurieInterface.OnCurieContainerReparented_BP
	// [Event, Public, BlueprintEvent]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void OnCurieContainerReparented_BP(const struct FCurieContainerHandle& CurieContainerHandle);

	// Function Curie.CurieInterface.OnCurieElementAttached_BP
	// [Event, Public, BlueprintEvent]
	// NumParams(2) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void OnCurieElementAttached_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag);

	// Function Curie.CurieInterface.OnCurieElementDetached_BP
	// [Event, Public, BlueprintEvent]
	// NumParams(2) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void OnCurieElementDetached_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag);

	// Function Curie.CurieInterface.OnCurieElementInteract_BP
	// [Event, Public, HasOutParams, BlueprintEvent]
	// NumParams(3) | ParamSize(0x18) | UObject::ProcessInternal(0x76106A4)
	void OnCurieElementInteract_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag, const struct FCurieInteractParamsHandle& InteractParamsHandle);

	// Function Curie.CurieInterface.OnCurieElementInteractBegun_BP
	// [Event, Public, HasOutParams, BlueprintEvent]
	// NumParams(3) | ParamSize(0x18) | UObject::ProcessInternal(0x76106A4)
	void OnCurieElementInteractBegun_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag, const struct FCurieInteractParamsHandle& InteractParamsHandle);

	// Function Curie.CurieInterface.OnCurieElementInteractEnded_BP
	// [Event, Public, HasOutParams, BlueprintEvent]
	// NumParams(3) | ParamSize(0x18) | UObject::ProcessInternal(0x76106A4)
	void OnCurieElementInteractEnded_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& ElementTag, const struct FCurieInteractParamsHandle& InteractParamsHandle);

	// Function Curie.CurieInterface.OnCurieStateAttached_BP
	// [Event, Public, BlueprintEvent]
	// NumParams(2) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void OnCurieStateAttached_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& StateTag);

	// Function Curie.CurieInterface.OnCurieStateDetached_BP
	// [Event, Public, BlueprintEvent]
	// NumParams(2) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void OnCurieStateDetached_BP(const struct FCurieContainerHandle& CurieContainerHandle, const struct FGameplayTag& StateTag);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieInterface")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieInterface")
	}
	static class ICurieInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<ICurieInterface>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ICurieInterface;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieElementGameplayEffectOwner
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0028) StructUnalignedSize(0x0028) StructAlignment(0x0008)
// 0x0000 (0x0028 - 0x0028)
class UCurieElementGameplayEffectOwner : public UObject
{
public:
	UCurieElementGameplayEffectOwner() {}

	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieElementGameplayEffectOwner")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieElementGameplayEffectOwner")
	}
	static class UCurieElementGameplayEffectOwner* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieElementGameplayEffectOwner>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieElementGameplayEffectOwner;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieElementInteractWithContainerHandler
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0070) StructUnalignedSize(0x0070) StructAlignment(0x0008)
// 0x0048 (0x0070 - 0x0028)
class UCurieElementInteractWithContainerHandler : public UCurieElementGameplayEffectOwner
{
public:
	UCurieElementInteractWithContainerHandler() {}

	EECurieHandlerPriority HandlerPriority; // 0x0028(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EECurieHandlerBehavior HandlerBehavior; // 0x0029(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8 Pad_2A[0x2]; // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag ElementTag; // 0x002C(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<struct FCurieEffectContainer> OnInstantInteractionEffects; // 0x0030(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	TArray<struct FCurieEffectContainer> OnBeginInteractionEffects; // 0x0040(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	TArray<struct FCurieEffectContainer> OngoingInteractionEffects; // 0x0050(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	TArray<struct FCurieEffectContainer> OnEndInteractionEffects; // 0x0060(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieElementInteractWithContainerHandler")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieElementInteractWithContainerHandler")
	}
	static class UCurieElementInteractWithContainerHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieElementInteractWithContainerHandler>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieElementInteractWithContainerHandler;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieElementAttachConditionHandler
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0030) StructUnalignedSize(0x0030) StructAlignment(0x0008)
// 0x0008 (0x0030 - 0x0028)
class UCurieElementAttachConditionHandler : public UObject
{
public:
	UCurieElementAttachConditionHandler() {}

	EECurieHandlerPriority HandlerPriority; // 0x0028(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8 Pad_29[0x3]; // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag ElementTag; // 0x002C(0x0004)(Edit, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieElementAttachConditionHandler")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieElementAttachConditionHandler")
	}
	static class UCurieElementAttachConditionHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieElementAttachConditionHandler>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieElementAttachConditionHandler;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieElementAttachHandler
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0060) StructUnalignedSize(0x0060) StructAlignment(0x0008)
// 0x0038 (0x0060 - 0x0028)
class UCurieElementAttachHandler : public UCurieElementGameplayEffectOwner
{
public:
	UCurieElementAttachHandler() {}

	EECurieHandlerPriority HandlerPriority; // 0x0028(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EECurieHandlerBehavior HandlerBehavior; // 0x0029(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8 Pad_2A[0x2]; // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag ElementTag; // 0x002C(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<struct FCurieEffectContainer> OnBeginAttachmentEffects; // 0x0030(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	TArray<struct FCurieEffectContainer> OngoingAttachmentEffects; // 0x0040(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	TArray<struct FCurieEffectContainer> OnEndAttachmentEffects; // 0x0050(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieElementAttachHandler")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieElementAttachHandler")
	}
	static class UCurieElementAttachHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieElementAttachHandler>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieElementAttachHandler;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieElementInteractWithMaterialHandler
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0030) StructUnalignedSize(0x0030) StructAlignment(0x0008)
// 0x0008 (0x0030 - 0x0028)
class UCurieElementInteractWithMaterialHandler : public UObject
{
public:
	UCurieElementInteractWithMaterialHandler() {}

	EECurieHandlerPriority HandlerPriority; // 0x0028(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EECurieHandlerBehavior HandlerBehavior; // 0x0029(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8 Pad_2A[0x2]; // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag ElementTag; // 0x002C(0x0004)(Edit, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieElementInteractWithMaterialHandler")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieElementInteractWithMaterialHandler")
	}
	static class UCurieElementInteractWithMaterialHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieElementInteractWithMaterialHandler>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieElementInteractWithMaterialHandler;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieElementInteractWithElementHandler
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0030) StructUnalignedSize(0x0030) StructAlignment(0x0008)
// 0x0008 (0x0030 - 0x0028)
class UCurieElementInteractWithElementHandler : public UObject
{
public:
	UCurieElementInteractWithElementHandler() {}

	EECurieHandlerPriority HandlerPriority; // 0x0028(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EECurieHandlerBehavior HandlerBehavior; // 0x0029(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8 Pad_2A[0x2]; // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag ElementTag; // 0x002C(0x0004)(Edit, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieElementInteractWithElementHandler")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieElementInteractWithElementHandler")
	}
	static class UCurieElementInteractWithElementHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieElementInteractWithElementHandler>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieElementInteractWithElementHandler;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieElementAllocationHandler
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0028) StructUnalignedSize(0x0028) StructAlignment(0x0008)
// 0x0000 (0x0028 - 0x0028)
class UCurieElementAllocationHandler : public UObject
{
public:
	UCurieElementAllocationHandler() {}

	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieElementAllocationHandler")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieElementAllocationHandler")
	}
	static class UCurieElementAllocationHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieElementAllocationHandler>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieElementAllocationHandler;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieGlobals
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0050) StructUnalignedSize(0x0050) StructAlignment(0x0008)
// 0x0028 (0x0050 - 0x0028)
class UCurieGlobals final : public UObject
{
public:
	UCurieGlobals() {}

	bool bEnableCurie; // 0x0028(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8 Pad_29[0x7]; // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftClassPath CurieGlobalsClassName; // 0x0030(0x0018)(ZeroConstructor, Config, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCurieManager* RegisteredCurieManager; // 0x0048(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieGlobals")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieGlobals")
	}
	static class UCurieGlobals* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieGlobals>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieGlobals;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieEntityStateBehavior
// SuperAlignedSize(0x0028) SuperUnalignedSize(0x0028) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00C0) StructUnalignedSize(0x00C0) StructAlignment(0x0008)
// 0x0098 (0x00C0 - 0x0028)
class UCurieEntityStateBehavior : public UCurieElementGameplayEffectOwner
{
public:
	UCurieEntityStateBehavior() {}

	struct FGameplayTagContainer RequiredAttachedElements; // 0x0028(0x0020)(Edit, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FGameplayTagContainer RequiredInteractingElements; // 0x0048(0x0020)(Edit, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FGameplayTagContainer AllowedAttachmentEntityTypes; // 0x0068(0x0020)(Edit, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TArray<struct FCurieEffectContainer> OnBeginEffects; // 0x0088(0x0010)(Edit, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TArray<struct FCurieEffectContainer> OngoingEffects; // 0x0098(0x0010)(Edit, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TArray<struct FCurieEffectContainer> OnEndEffects; // 0x00A8(0x0010)(Edit, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	uint8 bShouldDetach : 1; // 0x00B8(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8 bSkipExecuteAttachDetach : 1; // 0x00B8(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8 Pad_B9[0x7]; // 0x00B9(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieEntityStateBehavior")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieEntityStateBehavior")
	}
	static class UCurieEntityStateBehavior* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieEntityStateBehavior>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieEntityStateBehavior;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Class Curie.CurieComponent
// SuperAlignedSize(0x00A0) SuperUnalignedSize(0x00A0) SuperAlignment(0x0008) SuperLastMemberEnd(0x008F)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00B0) StructUnalignedSize(0x00B0) StructAlignment(0x0008)
// 0x0010 (0x00B0 - 0x00A0)
class UCurieComponent : public UActorComponent
{
public:
	UCurieComponent() {}

	uint8 Pad_A0[0x10]; // 0x00A0(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CurieComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CurieComponent")
	}
	static class UCurieComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurieComponent>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UCurieComponent;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
