#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: DiscoveryBrowserUI

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "FortniteGame_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function DiscoveryBrowserUI.FortActivityTileView.SetListenForMouseWheelInput
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileView_SetListenForMouseWheelInput final
{
public:
	UFortActivityTileView_SetListenForMouseWheelInput() {}

	bool bListenForInput; // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileView_SetListenForMouseWheelInput;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.OnIsFavoriteChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileDetailsDisplay_OnIsFavoriteChanged final
{
public:
	UFortActivityTileDetailsDisplay_OnIsFavoriteChanged() {}

	bool bIsFavorite; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_OnIsFavoriteChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.OnPartySizeChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct UFortActivityTileDetailsDisplay_OnPartySizeChanged final
{
public:
	UFortActivityTileDetailsDisplay_OnPartySizeChanged() {}

	int32 PartySize; // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_OnPartySizeChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.OnPreviewImageChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UFortActivityTileDetailsDisplay_OnPreviewImageChanged final
{
public:
	UFortActivityTileDetailsDisplay_OnPreviewImageChanged() {}

	bool bIsLoading; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1[0x7]; // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTexture* Texture; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_OnPreviewImageChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.OnRequiresPurchaseChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileDetailsDisplay_OnRequiresPurchaseChanged final
{
public:
	UFortActivityTileDetailsDisplay_OnRequiresPurchaseChanged() {}

	bool bRequiresPurchase; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_OnRequiresPurchaseChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.OnSocialUsersPlayingChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct UFortActivityTileDetailsDisplay_OnSocialUsersPlayingChanged final
{
public:
	UFortActivityTileDetailsDisplay_OnSocialUsersPlayingChanged() {}

	int32 NumPlaying; // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_OnSocialUsersPlayingChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.OnTileActiveSet
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileDetailsDisplay_OnTileActiveSet final
{
public:
	UFortActivityTileDetailsDisplay_OnTileActiveSet() {}

	bool bIsTileActive; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_OnTileActiveSet;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.DoesActivityRequirePurchase
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileDetailsDisplay_DoesActivityRequirePurchase final
{
public:
	UFortActivityTileDetailsDisplay_DoesActivityRequirePurchase() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_DoesActivityRequirePurchase;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.GetInvalidActivityReason
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileDetailsDisplay_GetInvalidActivityReason final
{
public:
	UFortActivityTileDetailsDisplay_GetInvalidActivityReason() {}

	EEFortInvalidActivityReason ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_GetInvalidActivityReason;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.IsActivityEpicCreated
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileDetailsDisplay_IsActivityEpicCreated final
{
public:
	UFortActivityTileDetailsDisplay_IsActivityEpicCreated() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_IsActivityEpicCreated;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.IsActivityFavorited
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileDetailsDisplay_IsActivityFavorited final
{
public:
	UFortActivityTileDetailsDisplay_IsActivityFavorited() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_IsActivityFavorited;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityTileDetailsDisplay.IsModeSetActivity
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityTileDetailsDisplay_IsModeSetActivity final
{
public:
	UFortActivityTileDetailsDisplay_IsModeSetActivity() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityTileDetailsDisplay_IsModeSetActivity;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserView.GetInvalidActivityReason
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserView_GetInvalidActivityReason final
{
public:
	UFortActivityBrowserView_GetInvalidActivityReason() {}

	EEFortInvalidActivityReason ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserView_GetInvalidActivityReason;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivitySearchView.HandleTextChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UFortActivitySearchView_HandleTextChanged final
{
public:
	UFortActivitySearchView_HandleTextChanged() {}

	class FText Text; // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivitySearchView_HandleTextChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivitySearchView.HandleTextCommitted
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0020) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct UFortActivitySearchView_HandleTextCommitted final
{
public:
	UFortActivitySearchView_HandleTextCommitted() {}

	class FText InText; // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	EETextCommit CommitInfo; // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_19[0x7]; // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivitySearchView_HandleTextCommitted;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivitySearchView.OnActivityValidated
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivitySearchView_OnActivityValidated final
{
public:
	UFortActivitySearchView_OnActivityValidated() {}

	EEFortActivityValidationResult ValidateResult; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivitySearchView_OnActivityValidated;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityModeSetSelectionModal.OnActivityChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UFortActivityModeSetSelectionModal_OnActivityChanged final
{
public:
	UFortActivityModeSetSelectionModal_OnActivityChanged() {}

	const class UFortGameActivity* GameActivity; // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString StartingSelectedMnemonic; // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityModeSetSelectionModal_OnActivityChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityModeSetSelectionModal.OnPreviewImageChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UFortActivityModeSetSelectionModal_OnPreviewImageChanged final
{
public:
	UFortActivityModeSetSelectionModal_OnPreviewImageChanged() {}

	bool bIsLoading; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1[0x7]; // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTexture* Texture; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityModeSetSelectionModal_OnPreviewImageChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityLobbyTile.OnPreviewImageChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UFortActivityLobbyTile_OnPreviewImageChanged final
{
public:
	UFortActivityLobbyTile_OnPreviewImageChanged() {}

	bool bIsLoading; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1[0x7]; // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTexture* Texture; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityLobbyTile_OnPreviewImageChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityLobbyTile.OnShowChildActivityChangedNotification
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UFortActivityLobbyTile_OnShowChildActivityChangedNotification final
{
public:
	UFortActivityLobbyTile_OnShowChildActivityChangedNotification() {}

	class FText DisplayName; // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityLobbyTile_OnShowChildActivityChangedNotification;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityLobbyTile.GetChildActivityDisplayName
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UFortActivityLobbyTile_GetChildActivityDisplayName final
{
public:
	UFortActivityLobbyTile_GetChildActivityDisplayName() {}

	class FText ReturnValue; // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityLobbyTile_GetChildActivityDisplayName;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityLobbyTile.IsActivityEpicCreated
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityLobbyTile_IsActivityEpicCreated final
{
public:
	UFortActivityLobbyTile_IsActivityEpicCreated() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityLobbyTile_IsActivityEpicCreated;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityLobbyTile.IsModeSetActivity
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityLobbyTile_IsModeSetActivity final
{
public:
	UFortActivityLobbyTile_IsModeSetActivity() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityLobbyTile_IsModeSetActivity;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityListView.GetInViewCount
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct UFortActivityListView_GetInViewCount final
{
public:
	UFortActivityListView_GetInViewCount() {}

	int32 ReturnValue; // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityListView_GetInViewCount;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRowView.OnRowChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct UFortActivityBrowserRowView_OnRowChanged final
{
public:
	UFortActivityBrowserRowView_OnRowChanged() {}

	int32 NewCategoryIndex; // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRowView_OnRowChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.OnMoviePlayingChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityDiscoverView_OnMoviePlayingChanged final
{
public:
	UFortActivityDiscoverView_OnMoviePlayingChanged() {}

	bool bIsPlaying; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_OnMoviePlayingChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.OnPreviewImageChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UFortActivityDiscoverView_OnPreviewImageChanged final
{
public:
	UFortActivityDiscoverView_OnPreviewImageChanged() {}

	bool bIsLoading; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1[0x7]; // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTexture* Texture; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_OnPreviewImageChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.GetCurrentTexture
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UFortActivityDiscoverView_GetCurrentTexture final
{
public:
	UFortActivityDiscoverView_GetCurrentTexture() {}

	const class UTexture* ReturnValue; // 0x0000(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_GetCurrentTexture;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.GetKeyArtOutroAnimation
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UFortActivityDiscoverView_GetKeyArtOutroAnimation final
{
public:
	UFortActivityDiscoverView_GetKeyArtOutroAnimation() {}

	class UWidgetAnimation* ReturnValue; // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_GetKeyArtOutroAnimation;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.GetMovieWidget
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UFortActivityDiscoverView_GetMovieWidget final
{
public:
	UFortActivityDiscoverView_GetMovieWidget() {}

	class UFortActivatableMovieWidget* ReturnValue; // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_GetMovieWidget;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.GetPromotedMovieWidget
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UFortActivityDiscoverView_GetPromotedMovieWidget final
{
public:
	UFortActivityDiscoverView_GetPromotedMovieWidget() {}

	class UFortActivatableMovieWidget* ReturnValue; // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_GetPromotedMovieWidget;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.IsImageLoading
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityDiscoverView_IsImageLoading final
{
public:
	UFortActivityDiscoverView_IsImageLoading() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_IsImageLoading;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.IsInOutroState
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityDiscoverView_IsInOutroState final
{
public:
	UFortActivityDiscoverView_IsInOutroState() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_IsInOutroState;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.IsShowingPromotedContent
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityDiscoverView_IsShowingPromotedContent final
{
public:
	UFortActivityDiscoverView_IsShowingPromotedContent() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_IsShowingPromotedContent;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityDiscoverView.IsShowingSeasonalContent
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityDiscoverView_IsShowingSeasonalContent final
{
public:
	UFortActivityDiscoverView_IsShowingSeasonalContent() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityDiscoverView_IsShowingSeasonalContent;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityCreateView.GetInvalidCreativeActivityReason
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityCreateView_GetInvalidCreativeActivityReason final
{
public:
	UFortActivityCreateView_GetInvalidCreativeActivityReason() {}

	EEFortInvalidActivityReason ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityCreateView_GetInvalidCreativeActivityReason;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityCategoryView.NavigateFromPanel
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UFortActivityCategoryView_NavigateFromPanel final
{
public:
	UFortActivityCategoryView_NavigateFromPanel() {}

	EEUINavigation Direction; // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1[0x7]; // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortActivityCategoryTilePanel* NavigatingPanel; // 0x0008(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFortActivityCategoryTilePanel* ReturnValue; // 0x0010(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityCategoryView_NavigateFromPanel;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityCategoryView.OnCategoryTilePanelSelected
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UFortActivityCategoryView_OnCategoryTilePanelSelected final
{
public:
	UFortActivityCategoryView_OnCategoryTilePanelSelected() {}

	const class UFortActivityCategoryTilePanel* SelectedPanel; // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityCategoryView_OnCategoryTilePanelSelected;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityCategoryView.GetCurrentSelectedPanel
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UFortActivityCategoryView_GetCurrentSelectedPanel final
{
public:
	UFortActivityCategoryView_GetCurrentSelectedPanel() {}

	const class UFortActivityCategoryTilePanel* ReturnValue; // 0x0000(0x0008)(ConstParm, ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityCategoryView_GetCurrentSelectedPanel;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityCategoryView.GetTopMostVisiblePanel
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0008)
// 0x0008 (0x0008 - 0x0000)
struct UFortActivityCategoryView_GetTopMostVisiblePanel final
{
public:
	UFortActivityCategoryView_GetTopMostVisiblePanel() {}

	class UFortActivityCategoryTilePanel* ReturnValue; // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityCategoryView_GetTopMostVisiblePanel;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityCategoryTile.OnTileActiveSet
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityCategoryTile_OnTileActiveSet final
{
public:
	UFortActivityCategoryTile_OnTileActiveSet() {}

	bool bIsTileActive; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityCategoryTile_OnTileActiveSet;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.OnCategoryItemChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_OnCategoryItemChanged final
{
public:
	UFortActivityBrowserRow_OnCategoryItemChanged() {}

	bool bPlayAnimation; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_OnCategoryItemChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.OnRowIsActiveChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_OnRowIsActiveChanged final
{
public:
	UFortActivityBrowserRow_OnRowIsActiveChanged() {}

	bool bIsActive; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_OnRowIsActiveChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.OnRowIsSelectedChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_OnRowIsSelectedChanged final
{
public:
	UFortActivityBrowserRow_OnRowIsSelectedChanged() {}

	bool bIsSelected; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_OnRowIsSelectedChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.OnRowMoveDown
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_OnRowMoveDown final
{
public:
	UFortActivityBrowserRow_OnRowMoveDown() {}

	bool bMovingOffscreen; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_OnRowMoveDown;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.OnRowMoveUp
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_OnRowMoveUp final
{
public:
	UFortActivityBrowserRow_OnRowMoveUp() {}

	bool bMovingOffscreen; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_OnRowMoveUp;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.OnRowPeekStateChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_OnRowPeekStateChanged final
{
public:
	UFortActivityBrowserRow_OnRowPeekStateChanged() {}

	bool bIsInPeekState; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_OnRowPeekStateChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.GetIsActive
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_GetIsActive final
{
public:
	UFortActivityBrowserRow_GetIsActive() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_GetIsActive;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.GetIsInPeekState
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_GetIsInPeekState final
{
public:
	UFortActivityBrowserRow_GetIsInPeekState() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_GetIsInPeekState;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRow.GetIsSelected
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRow_GetIsSelected final
{
public:
	UFortActivityBrowserRow_GetIsSelected() {}

	bool ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRow_GetIsSelected;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRowPromoted.OnPreviewImageChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UFortActivityBrowserRowPromoted_OnPreviewImageChanged final
{
public:
	UFortActivityBrowserRowPromoted_OnPreviewImageChanged() {}

	bool bIsLoading; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1[0x7]; // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTexture* Texture; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRowPromoted_OnPreviewImageChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserRowList.OnQueryStatusChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserRowList_OnQueryStatusChanged final
{
public:
	UFortActivityBrowserRowList_OnQueryStatusChanged() {}

	bool bIsActive; // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserRowList_OnQueryStatusChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowserTabButton.OnFavoriteChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowserTabButton_OnFavoriteChanged final
{
public:
	UFortActivityBrowserTabButton_OnFavoriteChanged() {}

	bool bIsFavorite; // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowserTabButton_OnFavoriteChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowser.HandleTabChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct UFortActivityBrowser_HandleTabChanged final
{
public:
	UFortActivityBrowser_HandleTabChanged() {}

	class FName TabId; // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowser_HandleTabChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowser.OnEnableColorScheme
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowser_OnEnableColorScheme final
{
public:
	UFortActivityBrowser_OnEnableColorScheme() {}

	bool bIsColorSchemeActive; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowser_OnEnableColorScheme;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowser.OnPlayerQueueTypeChanged
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowser_OnPlayerQueueTypeChanged final
{
public:
	UFortActivityBrowser_OnPlayerQueueTypeChanged() {}

	EEPlayerQueueType PlayerQueueType; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowser_OnPlayerQueueTypeChanged;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowser.OnSwapColorScheme
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowser_OnSwapColorScheme final
{
public:
	UFortActivityBrowser_OnSwapColorScheme() {}

	bool bInIsUsingAlternateColorScheme; // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowser_OnSwapColorScheme;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DiscoveryBrowserUI.FortActivityBrowser.OnUpdateCategoryPage
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UFortActivityBrowser_OnUpdateCategoryPage final
{
public:
	UFortActivityBrowser_OnUpdateCategoryPage() {}

	bool bShowCategoryPage; // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UFortActivityBrowser_OnUpdateCategoryPage;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
