#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: DuplicateResOutMesh

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.ExecuteUbergraph_DuplicateResOutMesh
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0210) StructUnalignedSize(0x0209) StructAlignment(0x0010)
// 0x0210 (0x0210 - 0x0000)
struct ADuplicateResOutMesh_C_ExecuteUbergraph_DuplicateResOutMesh final
{
public:
	ADuplicateResOutMesh_C_ExecuteUbergraph_DuplicateResOutMesh() {}

	int32 EntryPoint; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Array_Index_Variable; // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_IsValid_ReturnValue; // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_9[0x3]; // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 Temp_int_Loop_Counter_Variable; // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Add_IntInt_ReturnValue; // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None; // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_0; // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_1; // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_Divide_FloatFloat_ReturnValue; // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float K2Node_Event_DeltaSeconds; // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Array_Length_ReturnValue; // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_2C[0x4]; // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialInstanceDynamic*> K2Node_CustomEvent_MID_Array; // 0x0030(0x0010)(ConstParm, ReferenceParm)
	TArray<class USkeletalMeshComponent*> K2Node_CustomEvent_External_MEsh_Component_Array; // 0x0040(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	int32 None_2; // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_Less_IntInt_ReturnValue; // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_55[0x3]; // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 None_3; // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_4; // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent* CallFunc_Array_Get_Item; // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_SwitchEnum_CmpSuccess; // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_69[0x7]; // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform CallFunc_K2_GetComponentToWorld_ReturnValue; // 0x0070(0x0060)(IsPlainOldData, NoDestructor)
	class USkeletalMeshComponent* None_5; // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult CallFunc_K2_SetWorldTransform_SweepHitResult; // 0x00D8(0x00E0)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	TArray<class UMaterialInstanceDynamic*> CallFunc_External_Mesh_Masked_Setup_Corrected_Mid_Array; // 0x01B8(0x0010)(ReferenceParm)
	class USkeletalMeshComponent* None_6; // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_7; // 0x01D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_1D4[0x4]; // 0x01D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialInterface*> CallFunc_GetMaterials_ReturnValue; // 0x01D8(0x0010)(ReferenceParm)
	bool None_8; // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_1E9[0x3]; // 0x01E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 None_9; // 0x01EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_10; // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_1F1[0x3]; // 0x01F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 None_11; // 0x01F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_12; // 0x01F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_13; // 0x01FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic* None_14; // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_15; // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_ExecuteUbergraph_DuplicateResOutMesh;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.External Mesh Masked Setup
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0108) StructUnalignedSize(0x0104) StructAlignment(0x0008)
// 0x0108 (0x0108 - 0x0000)
struct ADuplicateResOutMesh_C_External_Mesh_Masked_Setup final
{
public:
	ADuplicateResOutMesh_C_External_Mesh_Masked_Setup() {}

	TArray<class USkeletalMeshComponent*> External_MEsh_Component_Array; // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UMaterialInstanceDynamic*> Corrected_Mid_Array; // 0x0010(0x0010)(Parm, OutParm)
	int32 Increment_MaskedSetup; // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_24[0x4]; // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialInstanceDynamic*> MID_Array_MaskedSetup; // 0x0028(0x0010)(Edit, BlueprintVisible)
	int32 CallFunc_Array_Length_ReturnValue; // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Array_Index_Variable; // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Loop_Counter_Variable; // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_44[0x4]; // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent* CallFunc_Array_Get_Item; // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInterface*> CallFunc_GetMaterials_ReturnValue; // 0x0050(0x0010)(ReferenceParm)
	bool CallFunc_Less_IntInt_ReturnValue; // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_61[0x3]; // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 None; // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_0; // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Add_IntInt_ReturnValue; // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_1; // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_74[0x4]; // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface* None_2; // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString CallFunc_GetDisplayName_ReturnValue; // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Array_Add_ReturnValue; // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_9C[0x4]; // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance* K2Node_DynamicCast_AsMaterial_Instance; // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_Array_Contains_ReturnValue; // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_AA[0x6]; // 0x00AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance* Temp_object_Variable; // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_3; // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_BooleanOR_ReturnValue; // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_BA[0x6]; // 0x00BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance* None_4; // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool Temp_bool_Variable; // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_C9[0x3]; // 0x00C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 None_5; // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstance* K2Node_Select_Default; // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic* None_6; // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_7; // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_8; // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic* None_9; // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic* None_10; // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_11; // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_12; // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_FD[0x3]; // 0x00FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 None_13; // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_External_Mesh_Masked_Setup;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.Find Bounds
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0370) StructUnalignedSize(0x0370) StructAlignment(0x0010)
// 0x0370 (0x0370 - 0x0000)
struct ADuplicateResOutMesh_C_Find_Bounds final
{
public:
	ADuplicateResOutMesh_C_Find_Bounds() {}

	bool Temp_bool_Variable; // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_1[0x7]; // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_BreakTransform_Location; // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator CallFunc_BreakTransform_Rotation; // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector CallFunc_BreakTransform_Scale; // 0x0038(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector None; // 0x0050(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator None_0; // 0x0068(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector None_1; // 0x0080(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_BreakVector_X; // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_BreakVector_Y; // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_BreakVector_Z; // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float None_2; // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float None_3; // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float None_4; // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_Multiply_FloatFloat_ReturnValue; // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_B4[0x4]; // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_MakeVector_ReturnValue; // 0x00B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector None_5; // 0x00D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_BreakRotIntoAxes_X; // 0x00E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_BreakRotIntoAxes_Y; // 0x0100(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_BreakRotIntoAxes_Z; // 0x0118(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct CoreUObject::FTransform CallFunc_MakeTransform_ReturnValue; // 0x0130(0x0060)(IsPlainOldData, NoDestructor)
	struct FRotator CallFunc_MakeRotationFromAxes_ReturnValue; // 0x0190(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8 Pad_1A8[0x8]; // 0x01A8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform None_6; // 0x01B0(0x0060)(IsPlainOldData, NoDestructor)
	struct CoreUObject::FTransform K2Node_Select_Default; // 0x0210(0x0060)(IsPlainOldData, NoDestructor)
	struct FVector None_7; // 0x0270(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator None_8; // 0x0288(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector None_9; // 0x02A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_GetActorBounds_Origin; // 0x02B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_GetActorBounds_BoxExtent; // 0x02D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_VSize_ReturnValue; // 0x02E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_2EC[0x4]; // 0x02EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_Multiply_VectorVector_ReturnValue; // 0x02F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_308[0x8]; // 0x0308(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform None_10; // 0x0310(0x0060)(IsPlainOldData, NoDestructor)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_Find_Bounds;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.initializeExternalSkeletalMeshArray
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0040) StructUnalignedSize(0x0039) StructAlignment(0x0008)
// 0x0040 (0x0040 - 0x0000)
struct ADuplicateResOutMesh_C_initializeExternalSkeletalMeshArray final
{
public:
	ADuplicateResOutMesh_C_initializeExternalSkeletalMeshArray() {}

	class APlayerPawn_Athena_Generic_Parent_C* K2Node_DynamicCast_AsPlayer_Pawn_Athena_Generic_Parent; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_9[0x7]; // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortAIPawn* K2Node_DynamicCast_AsFort_AIPawn; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None; // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_19[0x7]; // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class USkeletalMeshComponent*> K2Node_MakeArray_Array; // 0x0020(0x0010)(ReferenceParm, ContainsInstancedReference)
	class APlayerPawn_Generic_Parent_C* K2Node_DynamicCast_AsPlayer_Pawn_Generic_Parent; // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_0; // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_initializeExternalSkeletalMeshArray;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.Make and slave internal meshes
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0270) StructUnalignedSize(0x026D) StructAlignment(0x0010)
// 0x0270 (0x0270 - 0x0000)
struct ADuplicateResOutMesh_C_Make_and_slave_internal_meshes final
{
public:
	ADuplicateResOutMesh_C_Make_and_slave_internal_meshes() {}

	struct CoreUObject::FTransform Transform; // 0x0000(0x0060)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor)
	int32 Temp_int_Array_Index_Variable; // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Variable; // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_EqualEqual_IntInt_ReturnValue; // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_69[0x3]; // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 CallFunc_Add_IntInt_ReturnValue; // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct CoreUObject::FTransform CallFunc_MakeTransform_ReturnValue; // 0x0070(0x0060)(IsPlainOldData, NoDestructor)
	class USkeletalMeshComponent* CallFunc_AddComponent_ReturnValue; // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent* CallFunc_Array_Get_Item; // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent* None; // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_E8[0x8]; // 0x00E8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform CallFunc_K2_GetComponentToWorld_ReturnValue; // 0x00F0(0x0060)(IsPlainOldData, NoDestructor)
	struct FHitResult CallFunc_K2_SetWorldTransform_SweepHitResult; // 0x0150(0x00E0)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	int32 CallFunc_Array_Length_ReturnValue; // 0x0230(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool Temp_bool_Variable; // 0x0234(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_235[0x3]; // 0x0235(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 CallFunc_Array_Add_ReturnValue; // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_23C[0x4]; // 0x023C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent* None_0; // 0x0240(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent* K2Node_Select_Default; // 0x0248(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Loop_Counter_Variable; // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_Less_IntInt_ReturnValue; // 0x0254(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_255[0x3]; // 0x0255(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 None_1; // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_25C[0x4]; // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent* None_2; // 0x0260(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 None_3; // 0x0268(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_4; // 0x026C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_Make_and_slave_internal_meshes;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.Make internal mids and append external and intermal mids to mid array
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0088) StructUnalignedSize(0x0088) StructAlignment(0x0008)
// 0x0088 (0x0088 - 0x0000)
struct ADuplicateResOutMesh_C_Make_internal_mids_and_append_external_and_intermal_mids_to_mid_array final
{
public:
	ADuplicateResOutMesh_C_Make_internal_mids_and_append_external_and_intermal_mids_to_mid_array() {}

	class USkeletalMeshComponent* CurrentExternalSkeletalMeshComponent; // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstance* GunOrCharacterMaterialInstance; // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Loop_Counter_Variable; // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Add_IntInt_ReturnValue; // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Array_Index_Variable; // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Variable; // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_LessEqual_IntInt_ReturnValue; // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_21[0x3]; // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 None; // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent* CallFunc_Array_Get_Item; // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent* None_0; // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstance* Temp_object_Variable; // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Array_Add_ReturnValue; // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_4C[0x4]; // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance* None_1; // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface* CallFunc_GetMaterial_ReturnValue; // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent* None_2; // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Array_Length_ReturnValue; // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_GetNumMaterials_ReturnValue; // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_Less_IntInt_ReturnValue; // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_71[0x3]; // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32 CallFunc_Subtract_IntInt_ReturnValue; // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool Temp_bool_Variable; // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_79[0x7]; // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance* K2Node_Select_Default; // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_Make_internal_mids_and_append_external_and_intermal_mids_to_mid_array;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.ProcessSpawnInTimeline
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x02A0) StructUnalignedSize(0x0299) StructAlignment(0x0008)
// 0x02A0 (0x02A0 - 0x0000)
struct ADuplicateResOutMesh_C_ProcessSpawnInTimeline final
{
public:
	ADuplicateResOutMesh_C_ProcessSpawnInTimeline() {}

	float ZHeight; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float LightIntensity; // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float DissolveGradientPercentage; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float DissolveGradientDistance; // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor DissolveGradientBaseLocation; // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor DissolveGradientDirectionalColor; // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_Subtract_FloatFloat_ReturnValue; // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_Lerp_ReturnValue; // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Array_Index_Variable; // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_MakeLiteralFloat_ReturnValue; // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float None; // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_Multiply_FloatFloat_ReturnValue; // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult CallFunc_K2_SetWorldLocation_SweepHitResult; // 0x0048(0x00E0)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool CallFunc_IsValid_ReturnValue; // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_0; // 0x0129(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_12A[0x2]; // 0x012A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName CallFunc_MakeLiteralName_ReturnValue; // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName None_1; // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_134[0x4]; // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_GetSocketLocation_ReturnValue; // 0x0138(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector None_2; // 0x0150(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 Temp_int_Loop_Counter_Variable; // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_16C[0x4]; // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_Subtract_VectorVector_ReturnValue; // 0x0170(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_Normal_ReturnValue; // 0x0188(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Add_IntInt_ReturnValue; // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_1A4[0x4]; // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_Multiply_VectorFloat_ReturnValue; // 0x01A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor CallFunc_Conv_VectorToLinearColor_ReturnValue; // 0x01C0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector None_3; // 0x01D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_Add_VectorVector_ReturnValue; // 0x01E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector None_4; // 0x0200(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector None_5; // 0x0218(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_VLerp_ReturnValue; // 0x0230(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector None_6; // 0x0248(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector None_7; // 0x0260(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor None_8; // 0x0278(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CallFunc_VSize_ReturnValue; // 0x0288(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32 CallFunc_Array_Length_ReturnValue; // 0x028C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic* CallFunc_Array_Get_Item; // 0x0290(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_Less_IntInt_ReturnValue; // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_ProcessSpawnInTimeline;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.ReceiveTick
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct ADuplicateResOutMesh_C_ReceiveTick final
{
public:
	ADuplicateResOutMesh_C_ReceiveTick() {}

	float DeltaSeconds; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_ReceiveTick;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.RestoreInProgressRes
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct ADuplicateResOutMesh_C_RestoreInProgressRes final
{
public:
	ADuplicateResOutMesh_C_RestoreInProgressRes() {}

	TArray<class UMaterialInstanceDynamic*> CallFunc_External_Mesh_Masked_Setup_Corrected_Mid_Array; // 0x0000(0x0010)(ReferenceParm)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_RestoreInProgressRes;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.Spawn  Light
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0080) StructUnalignedSize(0x0078) StructAlignment(0x0010)
// 0x0080 (0x0080 - 0x0000)
struct ADuplicateResOutMesh_C_Spawn__Light final
{
public:
	ADuplicateResOutMesh_C_Spawn__Light() {}

	bool CallFunc_IsMobilePlatform_ReturnValue; // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_1[0xF]; // 0x0001(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform CallFunc_MakeTransform_ReturnValue; // 0x0010(0x0060)(IsPlainOldData, NoDestructor)
	class UPointLightComponent* CallFunc_AddComponent_ReturnValue; // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_Spawn__Light;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function DuplicateResOutMesh.DuplicateResOutMesh_C.UpdateExternalParameters
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0020) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct ADuplicateResOutMesh_C_UpdateExternalParameters final
{
public:
	ADuplicateResOutMesh_C_UpdateExternalParameters() {}

	TArray<class UMaterialInstanceDynamic*> MID_Array; // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<class USkeletalMeshComponent*> External_MEsh_Component_Array; // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_ADuplicateResOutMesh_C_UpdateExternalParameters;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
