#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: EventPlayerStatProfileSelectorEntry

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass EventPlayerStatProfileSelectorEntry.EventPlayerStatProfileSelectorEntry_C
// SuperAlignedSize(0x1050) SuperUnalignedSize(0x1050) SuperAlignment(0x0010) SuperLastMemberEnd(0x1048)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x1090) StructUnalignedSize(0x1088) StructAlignment(0x0010)
// 0x0040 (0x1090 - 0x1050)
class UEventPlayerStatProfileSelectorEntry_C final : public UFortEventPlayerStatProfileSelectorEntry
{
public:
	UEventPlayerStatProfileSelectorEntry_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x1050(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation* Selected; // 0x1058(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage* Image_SelectedBG; // 0x1060(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()> Hovered; // 0x1068(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()> Unhovered; // 0x1078(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:

	// Function EventPlayerStatProfileSelectorEntry.EventPlayerStatProfileSelectorEntry_C.ExecuteUbergraph_EventPlayerStatProfileSelectorEntry
	// [Final, UbergraphFunction]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_EventPlayerStatProfileSelectorEntry(int32 EntryPoint);

	// Function EventPlayerStatProfileSelectorEntry.EventPlayerStatProfileSelectorEntry_C.BP_OnUnhovered
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void BP_OnUnhovered();

	// Function EventPlayerStatProfileSelectorEntry.EventPlayerStatProfileSelectorEntry_C.BP_OnHovered
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void BP_OnHovered();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EventPlayerStatProfileSelectorEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"EventPlayerStatProfileSelectorEntry_C")
	}
	static class UEventPlayerStatProfileSelectorEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEventPlayerStatProfileSelectorEntry_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UEventPlayerStatProfileSelectorEntry_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
