#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_HidingProp_JumpOut

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_Athena_HidingProp_JumpOut.GA_Athena_HidingProp_JumpOut_C
// SuperAlignedSize(0x0B10) SuperUnalignedSize(0x0B10) SuperAlignment(0x0008) SuperLastMemberEnd(0x0B10)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0B18) StructUnalignedSize(0x0B18) StructAlignment(0x0008)
// 0x0008 (0x0B18 - 0x0B10)
class UGA_Athena_HidingProp_JumpOut_C final : public UFortGameplayAbility
{
public:
	UGA_Athena_HidingProp_JumpOut_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x0B10(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:

	// Function GA_Athena_HidingProp_JumpOut.GA_Athena_HidingProp_JumpOut_C.ExecuteUbergraph_GA_Athena_HidingProp_JumpOut
	// [Final, UbergraphFunction, HasDefaults]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_GA_Athena_HidingProp_JumpOut(int32 EntryPoint);

	// Function GA_Athena_HidingProp_JumpOut.GA_Athena_HidingProp_JumpOut_C.K2_ActivateAbility
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void K2_ActivateAbility();


	// Function GA_Athena_HidingProp_JumpOut.GA_Athena_HidingProp_JumpOut_C.K2_CanActivateAbility
	// [Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const]
	// NumParams(4) | ParamSize(0x71) | UObject::ProcessInternal(0x76106A4)
	bool K2_CanActivateAbility(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpecHandle& Handle, struct FGameplayTagContainer* RelevantTags) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Athena_HidingProp_JumpOut_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"GA_Athena_HidingProp_JumpOut_C")
	}
	static class UGA_Athena_HidingProp_JumpOut_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_HidingProp_JumpOut_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UGA_Athena_HidingProp_JumpOut_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
