#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_BoostJumpPack

#include "Basic.hpp"

#include "Enum_BoostJumpStates_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_BoostJumpPack.GA_BoostJumpPack_C
// SuperAlignedSize(0x0B30) SuperUnalignedSize(0x0B30) SuperAlignment(0x0008) SuperLastMemberEnd(0x0B2D)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0D50) StructUnalignedSize(0x0D4C) StructAlignment(0x0008)
// 0x0220 (0x0D50 - 0x0B30)
class UGA_BoostJumpPack_C : public UFortGameplayAbility_JumpBoostPack
{
public:
	UGA_BoostJumpPack_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x0B30(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float Jump_Multiple; // 0x0B38(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_B3C[0x4]; // 0x0B3C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector Basic_Jump_Z_Adjust; // 0x0B40(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector FinalJumpHeight; // 0x0B58(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEventData EventTriggerData; // 0x0B70(0x00B0)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool bJumpButtonHeld; // 0x0C20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool bHoverButtonHeld; // 0x0C21(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool bAtApex; // 0x0C22(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_C23[0x1]; // 0x0C23(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle JetpackEffectHandle; // 0x0C24(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_C2C[0x4]; // 0x0C2C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn* FortPlayerPawn; // 0x0C30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float FuelFudge; // 0x0C38(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle RegenEffectHandle; // 0x0C3C(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool bRegenEffectActive; // 0x0C44(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_C45[0x3]; // 0x0C45(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer BoostExecuteTags; // 0x0C48(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32 HoverButtonHeldCount; // 0x0C68(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_C6C[0x4]; // 0x0C6C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer HoverExecuteTags; // 0x0C70(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32 JumpButtonHeldCount; // 0x0C90(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_C94[0x4]; // 0x0C94(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer HoverReleaseTags; // 0x0C98(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	float TimeStartedHovering; // 0x0CB8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float TimeStartedFalling; // 0x0CBC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float EndHoverDelay; // 0x0CC0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float EndFallingDelay; // 0x0CC4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer BoostReleaseTags; // 0x0CC8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool bHasDied; // 0x0CE8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_CE9[0x3]; // 0x0CE9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag BoostCue; // 0x0CEC(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag BoostJumpPackCue; // 0x0CF0(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_CF4[0x4]; // 0x0CF4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass* JetpackInUseEffect; // 0x0CF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool TriggeredByJump; // 0x0D00(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_D01[0x7]; // 0x0D01(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer BlockExecuteTags; // 0x0D08(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass* JetpackInUseEffect_Alt; // 0x0D28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag HidingPropTag; // 0x0D30(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag ZiplineTag; // 0x0D34(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag GliderRedeployTag; // 0x0D38(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag InitialBoostCue; // 0x0D3C(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool bFirstBoost; // 0x0D40(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_D41[0x3]; // 0x0D41(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag BoostEndCue; // 0x0D44(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag BoostOutOfFuelEndCue; // 0x0D48(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Added_A54C58044C5CE8F3DABC60A214FC45E0
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Added_A54C58044C5CE8F3DABC60A214FC45E0();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Added_B611282348ECFDA3CD120D87734E357C
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Added_B611282348ECFDA3CD120D87734E357C();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Added_D3A68EA84FC920CD9E2949BE05D3A5AC
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Added_D3A68EA84FC920CD9E2949BE05D3A5AC();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Added_F6D39ED5491065B2594D37A44C404CA7
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Added_F6D39ED5491065B2594D37A44C404CA7();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Consider Starting Regen Effect
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Consider_Starting_Regen_Effect();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Consider Stopping Regen Effect
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Consider_Stopping_Regen_Effect();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Delay_ProcessAbilityStateMachine
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Delay_ProcessAbilityStateMachine();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.DetermineStateToTransitionTo
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void DetermineStateToTransitionTo(EEnum_BoostJumpStates* BoostState);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.ExecuteUbergraph_GA_BoostJumpPack
	// [Final, UbergraphFunction, HasDefaults]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_GA_BoostJumpPack(int32 EntryPoint);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Handle Jetpack Equipped
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Handle_Jetpack_Equipped();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.HandleBoostEnded
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void HandleBoostEnded();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.HandleBoostJump
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void HandleBoostJump();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.HandleCurrentBoostStateChanged
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(2) | ParamSize(0x2) | UObject::ProcessInternal(0x76106A4)
	void HandleCurrentBoostStateChanged(EEJumpBoostPackState PreviousState, EEJumpBoostPackState CurrentState_0);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.HandleFalling
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void HandleFalling();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.HandleHovering
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void HandleHovering();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.HandleIdle
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void HandleIdle(bool bForceEndHovering);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.HandleJetpackInitialBoost
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void HandleJetpackInitialBoost();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.IsUsingJetpackEffectActive
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	bool IsUsingJetpackEffectActive();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.K2_ActivateAbilityFromEvent
	// [Event, Protected, HasOutParams, BlueprintEvent]
	// NumParams(1) | ParamSize(0xB0) | UObject::ProcessInternal(0x76106A4)
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.K2_OnEndAbility
	// [Event, Protected, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void K2_OnEndAbility(bool bWasCancelled);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.On Reached Jump Apex
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void On_Reached_Jump_Apex();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.OnAbilityCanceled
	// [Event, Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnAbilityCanceled();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.OnCurrentStateChanged
	// [Event, Public, BlueprintEvent]
	// NumParams(2) | ParamSize(0x2) | UObject::ProcessInternal(0x76106A4)
	void OnCurrentStateChanged(EEJumpBoostPackState InPreviousState, EEJumpBoostPackState InCurrentState);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.OnEnterVehicle
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnEnterVehicle();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.OnFuelIsEmpty
	// [Event, Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnFuelIsEmpty();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.OnFuelIsFull
	// [Event, Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnFuelIsFull();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.OnPawnLanded
	// [HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0xE0) | UObject::ProcessInternal(0x76106A4)
	void OnPawnLanded(const struct FHitResult& Hit);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.OnSavedPawnChanged 
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(2) | ParamSize(0x10) | UObject::ProcessInternal(0x76106A4)
	void OnSavedPawnChanged_(class AFortPlayerPawn* PreviousPawn, class AFortPlayerPawn* NewPawn);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.PotentiallyEndHovering
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void PotentiallyEndHovering(bool bForceEndHovering);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.ProcessAbilityStateMachine
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void ProcessAbilityStateMachine();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.ProcessTriggerData
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ProcessTriggerData(const struct FGameplayTag& TagOne);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Reengage Falling Movement
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Reengage_Falling_Movement();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Reengage Hovering Movement
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Reengage_Hovering_Movement();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Reset Toggle Input State
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Reset_Toggle_Input_State();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.ResetTransitionVariables
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void ResetTransitionVariables(bool bForceEndHovering);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.SavePlayerPawn
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void SavePlayerPawn();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.SetCurrentBoostState
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void SetCurrentBoostState(EEJumpBoostPackState NewState);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.SetJumpHeight
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(3) | ParamSize(0x28) | UObject::ProcessInternal(0x76106A4)
	void SetJumpHeight(class AFortPlayerPawn* Pawn, class AFortPlayerPawn** Pawn_Out, struct FVector* Jump_Height);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Setup Notify at Apex
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void Setup_Notify_at_Apex(bool bNotifyApex);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Setup PlayerPawn
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Setup_PlayerPawn();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.SetupTransitionVariables
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void SetupTransitionVariables(const struct FGameplayTag& InTag);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Start Regen Effect
	// [Public, HasDefaults, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Start_Regen_Effect();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Stop Regen Effect
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Stop_Regen_Effect();

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.TransitionFromBoost
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void TransitionFromBoost(EEnum_BoostJumpStates* TargetBoostState);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.TransitionFromFalling
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void TransitionFromFalling(EEnum_BoostJumpStates* TargetBoostState);

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.TransitionFromHovering
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void TransitionFromHovering(EEnum_BoostJumpStates* TargetBoostState);


	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Get Player Pawn
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const]
	// NumParams(2) | ParamSize(0x10) | UObject::ProcessInternal(0x76106A4)
	class AFortPlayerPawn* Get_Player_Pawn(class UObject* Object) const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.GetFuel
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void GetFuel(float* Fuel) const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.GetMaxFuel
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void GetMaxFuel(float* MaxFuel) const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.GetReserveFuel
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	float GetReserveFuel() const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.IsBoostAllowed
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	bool IsBoostAllowed() const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.IsCurrentlyDead
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const]
	// NumParams(2) | ParamSize(0x5) | UObject::ProcessInternal(0x76106A4)
	bool IsCurrentlyDead(const struct FGameplayTag& TagOne) const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.K2_CanActivateAbility
	// [Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const]
	// NumParams(4) | ParamSize(0x71) | UObject::ProcessInternal(0x76106A4)
	bool K2_CanActivateAbility(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpecHandle& Handle, struct FGameplayTagContainer* RelevantTags) const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.K2_ShouldAbilityRespondToEvent
	// [Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const]
	// NumParams(3) | ParamSize(0xF9) | UObject::ProcessInternal(0x76106A4)
	bool K2_ShouldAbilityRespondToEvent(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayEventData& Payload) const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.NotInHidingSpot
	// [Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	bool NotInHidingSpot() const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.Reasons To Reset on Transition
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const]
	// NumParams(2) | ParamSize(0x5) | UObject::ProcessInternal(0x76106A4)
	bool Reasons_To_Reset_on_Transition(const struct FGameplayTag& tag) const;

	// Function GA_BoostJumpPack.GA_BoostJumpPack_C.TransitionFromIdle
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void TransitionFromIdle(EEnum_BoostJumpStates* TargetBoostState) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_BoostJumpPack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"GA_BoostJumpPack_C")
	}
	static class UGA_BoostJumpPack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_BoostJumpPack_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UGA_BoostJumpPack_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
