#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Constructor_HammerHitsHeal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Ninja_Tactical_MeleeHitsHeal_classes.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_Constructor_HammerHitsHeal.GA_Constructor_HammerHitsHeal_C
// SuperAlignedSize(0x0CA8) SuperUnalignedSize(0x0CA8) SuperAlignment(0x0008) SuperLastMemberEnd(0x0CA8)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0CD0) StructUnalignedSize(0x0CD0) StructAlignment(0x0008)
// 0x0028 (0x0CD0 - 0x0CA8)
class UGA_Constructor_HammerHitsHeal_C final : public UGA_Ninja_Tactical_MeleeHitsHeal_C
{
public:
	UGA_Constructor_HammerHitsHeal_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame_GA_Constructor_HammerHitsHeal_C; // 0x0CA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTagContainer TC_RequiredTags; // 0x0CB0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:

	// Function GA_Constructor_HammerHitsHeal.GA_Constructor_HammerHitsHeal_C.ExecuteUbergraph_GA_Constructor_HammerHitsHeal
	// [Final, UbergraphFunction, HasDefaults]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_GA_Constructor_HammerHitsHeal(int32 EntryPoint);

	// Function GA_Constructor_HammerHitsHeal.GA_Constructor_HammerHitsHeal_C.K2_ActivateAbilityFromEvent
	// [Event, Protected, HasOutParams, BlueprintEvent]
	// NumParams(1) | ParamSize(0xB0) | UObject::ProcessInternal(0x76106A4)
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData_0);

	// Function GA_Constructor_HammerHitsHeal.GA_Constructor_HammerHitsHeal_C.SetupAbility
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void SetupAbility(class UAbilitySystemComponent* AbilitySystem);


	// Function GA_Constructor_HammerHitsHeal.GA_Constructor_HammerHitsHeal_C.K2_ShouldAbilityRespondToEvent
	// [Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const]
	// NumParams(3) | ParamSize(0xF9) | UObject::ProcessInternal(0x76106A4)
	bool K2_ShouldAbilityRespondToEvent(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayEventData& Payload) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Constructor_HammerHitsHeal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"GA_Constructor_HammerHitsHeal_C")
	}
	static class UGA_Constructor_HammerHitsHeal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Constructor_HammerHitsHeal_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UGA_Constructor_HammerHitsHeal_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
