
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Interrogate_GC

#include "Basic.hpp"

#include "GA_Interrogate_GC_classes.hpp"
#include "GA_Interrogate_GC_parameters.hpp"


SDK_NAMESPACE_START

// Function GA_Interrogate_GC.GA_Interrogate_GC_C.ExecuteUbergraph_GA_Interrogate_GC
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32 EntryPoint (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Interrogate_GC_C::ExecuteUbergraph_GA_Interrogate_GC(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Interrogate_GC_C", "ExecuteUbergraph_GA_Interrogate_GC");

	Params::UGA_Interrogate_GC_C_ExecuteUbergraph_GA_Interrogate_GC Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Interrogate_GC.GA_Interrogate_GC_C.FailedToActivatePassiveAbility
// (Event, Public, BlueprintEvent)

void UGA_Interrogate_GC_C::FailedToActivatePassiveAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Interrogate_GC_C", "FailedToActivatePassiveAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Interrogate_GC.GA_Interrogate_GC_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Interrogate_GC_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Interrogate_GC_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
