#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCL_Cornfield_Movement

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCL_Cornfield_Movement.GCL_Cornfield_Movement_C
// SuperAlignedSize(0x0920) SuperUnalignedSize(0x091D) SuperAlignment(0x0008) SuperLastMemberEnd(0x0919)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(true)
// StructAlignedSize(0x0928) StructUnalignedSize(0x0928) StructAlignment(0x0008)
// 0x000B (0x0928 - 0x091D)
class AGCL_Cornfield_Movement_C final : public AFortGameplayCueNotify_Loop
{
public:
	AGCL_Cornfield_Movement_C() {}

	uint8 Pad_91D[0x3]; // 0x091D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn* TargetPawn; // 0x0920(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:

	// Function GCL_Cornfield_Movement.GCL_Cornfield_Movement_C.OnActive
	// [Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(3) | ParamSize(0xD9) | UObject::ProcessInternal(0x76106A4)
	bool OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

	// Function GCL_Cornfield_Movement.GCL_Cornfield_Movement_C.OnRemove
	// [Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(3) | ParamSize(0xD9) | UObject::ProcessInternal(0x76106A4)
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCL_Cornfield_Movement_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"GCL_Cornfield_Movement_C")
	}
	static class AGCL_Cornfield_Movement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCL_Cornfield_Movement_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AGCL_Cornfield_Movement_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
