#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Athena_HidingProp_Wobble

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_Athena_HidingProp_Wobble.GCN_Athena_HidingProp_Wobble_C
// SuperAlignedSize(0x0200) SuperUnalignedSize(0x0200) SuperAlignment(0x0008) SuperLastMemberEnd(0x01F8)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0200) StructUnalignedSize(0x0200) StructAlignment(0x0008)
// 0x0000 (0x0200 - 0x0200)
class UGCN_Athena_HidingProp_Wobble_C final : public UFortGameplayCueNotify_Burst
{
public:
	UGCN_Athena_HidingProp_Wobble_C() {}


	// Function GCN_Athena_HidingProp_Wobble.GCN_Athena_HidingProp_Wobble_C.OnBurst
	// [Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const]
	// NumParams(6) | ParamSize(0x108) | UObject::ProcessInternal(0x76106A4)
	void OnBurst(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Athena_HidingProp_Wobble_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"GCN_Athena_HidingProp_Wobble_C")
	}
	static class UGCN_Athena_HidingProp_Wobble_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Athena_HidingProp_Wobble_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UGCN_Athena_HidingProp_Wobble_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
