#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Irwin_Swim

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function GCNL_Irwin_Swim.GCNL_Irwin_Swim_C.ExecuteUbergraph_GCNL_Irwin_Swim
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0170) StructUnalignedSize(0x0170) StructAlignment(0x0008)
// 0x0170 (0x0170 - 0x0000)
struct AGCNL_Irwin_Swim_C_ExecuteUbergraph_GCNL_Irwin_Swim final
{
public:
	AGCNL_Irwin_Swim_C_ExecuteUbergraph_GCNL_Irwin_Swim() {}

	int32 EntryPoint; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_4[0x4]; // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector CallFunc_GetWaterSurfaceNormal_ReturnValue; // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector CallFunc_GetWaterSurfaceLocation_ReturnValue; // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor* K2Node_Event_MyTarget; // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters K2Node_Event_Parameters; // 0x0040(0x00D0)(ConstParm, ContainsInstancedReference)
	TArray<class UFXSystemComponent*> K2Node_Event_ParticleComponents; // 0x0110(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UAudioComponent*> K2Node_Event_AudioComponents; // 0x0120(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	float CallFunc_GetWaterImmersionDepth_ReturnValue; // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_134[0x4]; // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemComponent* CallFunc_Array_Get_Item; // 0x0138(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortAIPawn* K2Node_DynamicCast_AsFort_AIPawn; // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_IsValid_ReturnValue; // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_IsSurfaceSwimming_ReturnValue; // 0x014A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_14B[0x5]; // 0x014B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortMovementComp_AIChar* K2Node_DynamicCast_AsFort_Movement_Comp_AIChar; // 0x0150(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None; // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_159[0x7]; // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortWaterBodyActor* CallFunc_GetCurrentWaterBody_ReturnValue; // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_0; // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool CallFunc_BooleanOR_ReturnValue; // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_16A[0x2]; // 0x016A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float K2Node_Event_DeltaSeconds; // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AGCNL_Irwin_Swim_C_ExecuteUbergraph_GCNL_Irwin_Swim;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function GCNL_Irwin_Swim.GCNL_Irwin_Swim_C.OnLoopingStartGeneric
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00F8) StructUnalignedSize(0x00F8) StructAlignment(0x0008)
// 0x00F8 (0x00F8 - 0x0000)
struct AGCNL_Irwin_Swim_C_OnLoopingStartGeneric final
{
public:
	AGCNL_Irwin_Swim_C_OnLoopingStartGeneric() {}

	class AActor* MyTarget; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters Parameters; // 0x0008(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UFXSystemComponent*> ParticleComponents; // 0x00D8(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UAudioComponent*> AudioComponents; // 0x00E8(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AGCNL_Irwin_Swim_C_OnLoopingStartGeneric;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function GCNL_Irwin_Swim.GCNL_Irwin_Swim_C.ReceiveTick
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0004) StructUnalignedSize(0x0004) StructAlignment(0x0004)
// 0x0004 (0x0004 - 0x0000)
struct AGCNL_Irwin_Swim_C_ReceiveTick final
{
public:
	AGCNL_Irwin_Swim_C_ReceiveTick() {}

	float DeltaSeconds; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AGCNL_Irwin_Swim_C_ReceiveTick;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
