#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Athena_Surface_Parent

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function GCNL_Athena_Surface_Parent.GCNL_Athena_Surface_Parent_C.ExecuteUbergraph_GCNL_Athena_Surface_Parent
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0230) StructUnalignedSize(0x0229) StructAlignment(0x0008)
// 0x0230 (0x0230 - 0x0000)
struct AGCNL_Athena_Surface_Parent_C_ExecuteUbergraph_GCNL_Athena_Surface_Parent final
{
public:
	AGCNL_Athena_Surface_Parent_C_ExecuteUbergraph_GCNL_Athena_Surface_Parent() {}

	int32 EntryPoint; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()> K2Node_CreateDelegate_OutputDelegate; // 0x0004(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor* None; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters None_0; // 0x0018(0x00D0)(ConstParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*> None_1; // 0x00E8(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UAudioComponent*> None_2; // 0x00F8(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	class AActor* K2Node_Event_MyTarget; // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters K2Node_Event_Parameters; // 0x0110(0x00D0)(ConstParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*> K2Node_Event_ParticleComponents; // 0x01E0(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UAudioComponent*> K2Node_Event_AudioComponents; // 0x01F0(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	class UMatineeCameraShake* K2Node_Event_BurstCameraShakeInstance; // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor* K2Node_Event_BurstDecalInstance; // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn* K2Node_DynamicCast_AsFort_Player_Pawn; // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_219[0x7]; // 0x0219(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn* None_3; // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool None_4; // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AGCNL_Athena_Surface_Parent_C_ExecuteUbergraph_GCNL_Athena_Surface_Parent;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function GCNL_Athena_Surface_Parent.GCNL_Athena_Surface_Parent_C.OnLoopingStart
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00F8) StructUnalignedSize(0x00F8) StructAlignment(0x0008)
// 0x00F8 (0x00F8 - 0x0000)
struct AGCNL_Athena_Surface_Parent_C_OnLoopingStart final
{
public:
	AGCNL_Athena_Surface_Parent_C_OnLoopingStart() {}

	class AActor* MyTarget; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters Parameters; // 0x0008(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*> ParticleComponents; // 0x00D8(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UAudioComponent*> AudioComponents; // 0x00E8(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AGCNL_Athena_Surface_Parent_C_OnLoopingStart;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function GCNL_Athena_Surface_Parent.GCNL_Athena_Surface_Parent_C.OnPlayerFootstep
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0009) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct AGCNL_Athena_Surface_Parent_C_OnPlayerFootstep final
{
public:
	AGCNL_Athena_Surface_Parent_C_OnPlayerFootstep() {}

	class APlayerPawn_Athena_C* K2Node_DynamicCast_AsPlayer_Pawn_Athena; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_DynamicCast_bSuccess; // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AGCNL_Athena_Surface_Parent_C_OnPlayerFootstep;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function GCNL_Athena_Surface_Parent.GCNL_Athena_Surface_Parent_C.OnRemoval
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0108) StructUnalignedSize(0x0108) StructAlignment(0x0008)
// 0x0108 (0x0108 - 0x0000)
struct AGCNL_Athena_Surface_Parent_C_OnRemoval final
{
public:
	AGCNL_Athena_Surface_Parent_C_OnRemoval() {}

	class AActor* MyTarget; // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters Parameters; // 0x0008(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*> ParticleComponents; // 0x00D8(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UAudioComponent*> AudioComponents; // 0x00E8(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class UMatineeCameraShake* BurstCameraShakeInstance; // 0x00F8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor* BurstDecalInstance; // 0x0100(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_AGCNL_Athena_Surface_Parent_C_OnRemoval;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
