#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: MotionWarping

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "MotionWarping_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function MotionWarping.RootMotionModifier_SkewWarp.AddRootMotionModifierSkewWarp
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00A0) StructUnalignedSize(0x00A0) StructAlignment(0x0010)
// 0x00A0 (0x00A0 - 0x0000)
struct URootMotionModifier_SkewWarp_AddRootMotionModifierSkewWarp final
{
public:
	URootMotionModifier_SkewWarp_AddRootMotionModifierSkewWarp() {}

	class UMotionWarpingComponent* InMotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimSequenceBase* InAnimation; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float InStartTime; // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float InEndTime; // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName InWarpTargetName; // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EEWarpPointAnimProvider InWarpPointAnimProvider; // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1D[0x3]; // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform InWarpPointAnimTransform; // 0x0020(0x0060)(Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class FName InWarpPointAnimBoneName; // 0x0080(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bInWarpTranslation; // 0x0084(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bInIgnoreZAxis; // 0x0085(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bInWarpRotation; // 0x0086(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EEMotionWarpRotationType InRotationType; // 0x0087(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float InWarpRotationTimeMultiplier; // 0x0088(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_8C[0x4]; // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URootMotionModifier_SkewWarp* ReturnValue; // 0x0090(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_98[0x8]; // 0x0098(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_URootMotionModifier_SkewWarp_AddRootMotionModifierSkewWarp;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.RootMotionModifier_AdjustmentBlendWarp.AddRootMotionModifierAdjustmentBlendWarp
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x00A0) StructUnalignedSize(0x00A0) StructAlignment(0x0010)
// 0x00A0 (0x00A0 - 0x0000)
struct URootMotionModifier_AdjustmentBlendWarp_AddRootMotionModifierAdjustmentBlendWarp final
{
public:
	URootMotionModifier_AdjustmentBlendWarp_AddRootMotionModifierAdjustmentBlendWarp() {}

	class UMotionWarpingComponent* InMotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimSequenceBase* InAnimation; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float InStartTime; // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float InEndTime; // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName InWarpTargetName; // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EEWarpPointAnimProvider InWarpPointAnimProvider; // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_1D[0x3]; // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform InWarpPointAnimTransform; // 0x0020(0x0060)(Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class FName InWarpPointAnimBoneName; // 0x0080(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bInWarpTranslation; // 0x0084(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bInIgnoreZAxis; // 0x0085(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bInWarpRotation; // 0x0086(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bInWarpIKBones; // 0x0087(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName> InIKBones; // 0x0088(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	class URootMotionModifier_AdjustmentBlendWarp* ReturnValue; // 0x0098(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_URootMotionModifier_AdjustmentBlendWarp_AddRootMotionModifierAdjustmentBlendWarp;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.RootMotionModifier_AdjustmentBlendWarp.GetAdjustmentBlendIKBoneTransformAndAlpha
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0080) StructUnalignedSize(0x0080) StructAlignment(0x0010)
// 0x0080 (0x0080 - 0x0000)
struct URootMotionModifier_AdjustmentBlendWarp_GetAdjustmentBlendIKBoneTransformAndAlpha final
{
public:
	URootMotionModifier_AdjustmentBlendWarp_GetAdjustmentBlendIKBoneTransformAndAlpha() {}

	class ACharacter* Character; // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName BoneName; // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_C[0x4]; // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform OutTransform; // 0x0010(0x0060)(Parm, OutParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	float OutAlpha; // 0x0070(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_74[0xC]; // 0x0074(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_URootMotionModifier_AdjustmentBlendWarp_GetAdjustmentBlendIKBoneTransformAndAlpha;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingComponent.AddOrUpdateWarpTarget
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0048) StructUnalignedSize(0x0048) StructAlignment(0x0008)
// 0x0048 (0x0048 - 0x0000)
struct UMotionWarpingComponent_AddOrUpdateWarpTarget final
{
public:
	UMotionWarpingComponent_AddOrUpdateWarpTarget() {}

	struct FMotionWarpingTarget WarpTarget; // 0x0000(0x0048)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingComponent_AddOrUpdateWarpTarget;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingComponent.AddOrUpdateWarpTargetFromComponent
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UMotionWarpingComponent_AddOrUpdateWarpTargetFromComponent final
{
public:
	UMotionWarpingComponent_AddOrUpdateWarpTargetFromComponent() {}

	class FName WarpTargetName; // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_4[0x4]; // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class USceneComponent* Component; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName BoneName; // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool bFollowComponent; // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_15[0x3]; // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingComponent_AddOrUpdateWarpTargetFromComponent;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingComponent.AddOrUpdateWarpTargetFromLocation
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0020) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct UMotionWarpingComponent_AddOrUpdateWarpTargetFromLocation final
{
public:
	UMotionWarpingComponent_AddOrUpdateWarpTargetFromLocation() {}

	class FName WarpTargetName; // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_4[0x4]; // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector TargetLocation; // 0x0008(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingComponent_AddOrUpdateWarpTargetFromLocation;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingComponent.AddOrUpdateWarpTargetFromLocationAndRotation
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0038) StructUnalignedSize(0x0038) StructAlignment(0x0008)
// 0x0038 (0x0038 - 0x0000)
struct UMotionWarpingComponent_AddOrUpdateWarpTargetFromLocationAndRotation final
{
public:
	UMotionWarpingComponent_AddOrUpdateWarpTargetFromLocationAndRotation() {}

	class FName WarpTargetName; // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_4[0x4]; // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector TargetLocation; // 0x0008(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator TargetRotation; // 0x0020(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingComponent_AddOrUpdateWarpTargetFromLocationAndRotation;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingComponent.AddOrUpdateWarpTargetFromTransform
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0070) StructUnalignedSize(0x0070) StructAlignment(0x0010)
// 0x0070 (0x0070 - 0x0000)
struct UMotionWarpingComponent_AddOrUpdateWarpTargetFromTransform final
{
public:
	UMotionWarpingComponent_AddOrUpdateWarpTargetFromTransform() {}

	class FName WarpTargetName; // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_4[0xC]; // 0x0004(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct CoreUObject::FTransform TargetTransform; // 0x0010(0x0060)(Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingComponent_AddOrUpdateWarpTargetFromTransform;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingComponent.RemoveWarpTarget
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0008) StructAlignment(0x0004)
// 0x0008 (0x0008 - 0x0000)
struct UMotionWarpingComponent_RemoveWarpTarget final
{
public:
	UMotionWarpingComponent_RemoveWarpTarget() {}

	class FName WarpTargetName; // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32 ReturnValue; // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingComponent_RemoveWarpTarget;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingUtilities.ExtractRootMotionFromAnimation
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0070) StructUnalignedSize(0x0070) StructAlignment(0x0010)
// 0x0070 (0x0070 - 0x0000)
struct UMotionWarpingUtilities_ExtractRootMotionFromAnimation final
{
public:
	UMotionWarpingUtilities_ExtractRootMotionFromAnimation() {}

	const class UAnimSequenceBase* Animation; // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float StartTime; // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float EndTime; // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct CoreUObject::FTransform ReturnValue; // 0x0010(0x0060)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingUtilities_ExtractRootMotionFromAnimation;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingUtilities.GetMotionWarpingWindowsForWarpTargetFromAnimation
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0020) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct UMotionWarpingUtilities_GetMotionWarpingWindowsForWarpTargetFromAnimation final
{
public:
	UMotionWarpingUtilities_GetMotionWarpingWindowsForWarpTargetFromAnimation() {}

	const class UAnimSequenceBase* Animation; // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName WarpTargetName; // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8 Pad_C[0x4]; // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FMotionWarpingWindowData> OutWindows; // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingUtilities_GetMotionWarpingWindowsForWarpTargetFromAnimation;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.MotionWarpingUtilities.GetMotionWarpingWindowsFromAnimation
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UMotionWarpingUtilities_GetMotionWarpingWindowsFromAnimation final
{
public:
	UMotionWarpingUtilities_GetMotionWarpingWindowsFromAnimation() {}

	const class UAnimSequenceBase* Animation; // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FMotionWarpingWindowData> OutWindows; // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotionWarpingUtilities_GetMotionWarpingWindowsFromAnimation;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.AnimNotifyState_MotionWarping.AddRootMotionModifier
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0020) StructUnalignedSize(0x0020) StructAlignment(0x0008)
// 0x0020 (0x0020 - 0x0000)
struct UAnimNotifyState_MotionWarping_AddRootMotionModifier final
{
public:
	UAnimNotifyState_MotionWarping_AddRootMotionModifier() {}

	class UMotionWarpingComponent* MotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimSequenceBase* Animation; // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float StartTime; // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float EndTime; // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class URootMotionModifier* ReturnValue; // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAnimNotifyState_MotionWarping_AddRootMotionModifier;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.AnimNotifyState_MotionWarping.OnRootMotionModifierActivate
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UAnimNotifyState_MotionWarping_OnRootMotionModifierActivate final
{
public:
	UAnimNotifyState_MotionWarping_OnRootMotionModifierActivate() {}

	class UMotionWarpingComponent* MotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class URootMotionModifier* Modifier; // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAnimNotifyState_MotionWarping_OnRootMotionModifierActivate;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.AnimNotifyState_MotionWarping.OnRootMotionModifierDeactivate
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UAnimNotifyState_MotionWarping_OnRootMotionModifierDeactivate final
{
public:
	UAnimNotifyState_MotionWarping_OnRootMotionModifierDeactivate() {}

	class UMotionWarpingComponent* MotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class URootMotionModifier* Modifier; // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAnimNotifyState_MotionWarping_OnRootMotionModifierDeactivate;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.AnimNotifyState_MotionWarping.OnRootMotionModifierUpdate
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UAnimNotifyState_MotionWarping_OnRootMotionModifierUpdate final
{
public:
	UAnimNotifyState_MotionWarping_OnRootMotionModifierUpdate() {}

	class UMotionWarpingComponent* MotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class URootMotionModifier* Modifier; // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAnimNotifyState_MotionWarping_OnRootMotionModifierUpdate;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.AnimNotifyState_MotionWarping.OnWarpBegin
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UAnimNotifyState_MotionWarping_OnWarpBegin final
{
public:
	UAnimNotifyState_MotionWarping_OnWarpBegin() {}

	class UMotionWarpingComponent* MotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class URootMotionModifier* Modifier; // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAnimNotifyState_MotionWarping_OnWarpBegin;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.AnimNotifyState_MotionWarping.OnWarpEnd
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UAnimNotifyState_MotionWarping_OnWarpEnd final
{
public:
	UAnimNotifyState_MotionWarping_OnWarpEnd() {}

	class UMotionWarpingComponent* MotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class URootMotionModifier* Modifier; // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAnimNotifyState_MotionWarping_OnWarpEnd;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function MotionWarping.AnimNotifyState_MotionWarping.OnWarpUpdate
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0010) StructUnalignedSize(0x0010) StructAlignment(0x0008)
// 0x0010 (0x0010 - 0x0000)
struct UAnimNotifyState_MotionWarping_OnWarpUpdate final
{
public:
	UAnimNotifyState_MotionWarping_OnWarpUpdate() {}

	class UMotionWarpingComponent* MotionWarpingComp; // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class URootMotionModifier* Modifier; // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UAnimNotifyState_MotionWarping_OnWarpUpdate;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
