#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: MotorSimOutputMotoSynth

#include "Basic.hpp"

#include "MotoSynth_classes.hpp"


SDK_NAMESPACE_START

// Class MotorSimOutputMotoSynth.MotorSimOutputMotoSynth
// SuperAlignedSize(0x0910) SuperUnalignedSize(0x0910) SuperAlignment(0x0010) SuperLastMemberEnd(0x077C)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0910) StructUnalignedSize(0x0910) StructAlignment(0x0010)
// 0x0000 (0x0910 - 0x0910)
class UMotorSimOutputMotoSynth final : public USynthComponentMoto
{
public:
	UMotorSimOutputMotoSynth() {}

	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MotorSimOutputMotoSynth")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"MotorSimOutputMotoSynth")
	}
	static class UMotorSimOutputMotoSynth* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMotorSimOutputMotoSynth>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMotorSimOutputMotoSynth;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
