#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: MTXButton

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass MTXButton.MTXButton_C
// SuperAlignedSize(0x1030) SuperUnalignedSize(0x1030) SuperAlignment(0x0010) SuperLastMemberEnd(0x1030)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x1070) StructUnalignedSize(0x1070) StructAlignment(0x0010)
// 0x0040 (0x1070 - 0x1030)
class UMTXButton_C final : public UFortMTXButton
{
public:
	UMTXButton_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x1030(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation* Hover_Grow; // 0x1038(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation* Hover_Bounce; // 0x1040(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation* Hover; // 0x1048(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBorder* AmountColor; // 0x1050(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage* ButtonBacking; // 0x1058(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage* Image_Vbucks; // 0x1060(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox* VariableSize; // 0x1068(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:

	// Function MTXButton.MTXButton_C.ExecuteUbergraph_MTXButton
	// [Final, UbergraphFunction]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_MTXButton(int32 EntryPoint);

	// Function MTXButton.MTXButton_C.Construct
	// [BlueprintCosmetic, Event, Public, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Construct();

	// Function MTXButton.MTXButton_C.BP_OnUnhovered
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void BP_OnUnhovered();

	// Function MTXButton.MTXButton_C.BP_OnHovered
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void BP_OnHovered();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MTXButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"MTXButton_C")
	}
	static class UMTXButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMTXButton_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UMTXButton_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
