
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Pawn_Irwin_Prey_Burt

#include "Basic.hpp"

#include "NPC_Pawn_Irwin_Prey_Burt_classes.hpp"
#include "NPC_Pawn_Irwin_Prey_Burt_parameters.hpp"


SDK_NAMESPACE_START

// Function NPC_Pawn_Irwin_Prey_Burt.NPC_Pawn_Irwin_Prey_Burt_C.ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Burt
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32 EntryPoint (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Burt_C::ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Burt(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Burt_C", "ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Burt");

	Params::ANPC_Pawn_Irwin_Prey_Burt_C_ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Burt Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Burt.NPC_Pawn_Irwin_Prey_Burt_C.OnEnteredWaterBody
// (Event, Public, BlueprintEvent)
// Parameters:
// class AFortWaterBodyActor* WaterBody (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool bIsFirstBody (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Burt_C::OnEnteredWaterBody(class AFortWaterBodyActor* WaterBody, bool bIsFirstBody)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Burt_C", "OnEnteredWaterBody");

	Params::ANPC_Pawn_Irwin_Prey_Burt_C_OnEnteredWaterBody Parms{};

	*reinterpret_cast<void**>(&Parms.WaterBody) = reinterpret_cast<void*>(WaterBody);
	Parms.bIsFirstBody = bIsFirstBody;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Burt.NPC_Pawn_Irwin_Prey_Burt_C.OnExitedWaterBody
// (Event, Public, BlueprintEvent)
// Parameters:
// class AFortWaterBodyActor* WaterBody (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool bIsLastBody (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Burt_C::OnExitedWaterBody(class AFortWaterBodyActor* WaterBody, bool bIsLastBody)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Burt_C", "OnExitedWaterBody");

	Params::ANPC_Pawn_Irwin_Prey_Burt_C_OnExitedWaterBody Parms{};

	*reinterpret_cast<void**>(&Parms.WaterBody) = reinterpret_cast<void*>(WaterBody);
	Parms.bIsLastBody = bIsLastBody;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Burt.NPC_Pawn_Irwin_Prey_Burt_C.OnLanded
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult& Hit (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ANPC_Pawn_Irwin_Prey_Burt_C::OnLanded(const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Burt_C", "OnLanded");

	Params::ANPC_Pawn_Irwin_Prey_Burt_C_OnLanded Parms{};

	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Burt.NPC_Pawn_Irwin_Prey_Burt_C.BlueprintCanInteract
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const class AFortPawn* InteractingPawn (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const EEInteractionBeingAttempted InteractionBeingAttempted (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool ReturnValue (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ANPC_Pawn_Irwin_Prey_Burt_C::BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EEInteractionBeingAttempted InteractionBeingAttempted) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Burt_C", "BlueprintCanInteract");

	Params::ANPC_Pawn_Irwin_Prey_Burt_C_BlueprintCanInteract Parms{};

	*reinterpret_cast<const void**>(&Parms.InteractingPawn) = reinterpret_cast<const void*>(InteractingPawn);
	Parms.InteractionBeingAttempted = InteractionBeingAttempted;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
