#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPCStatusWidget

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass NPCStatusWidget.NPCStatusWidget_C
// SuperAlignedSize(0x0390) SuperUnalignedSize(0x0390) SuperAlignment(0x0008) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x03E8) StructUnalignedSize(0x03E8) StructAlignment(0x0008)
// 0x0058 (0x03E8 - 0x0390)
class UNPCStatusWidget_C final : public UNPCStatusWidgetBase
{
public:
	UNPCStatusWidget_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNPCStatusWidgetBar_C* Bar_Health; // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNPCStatusWidgetBar_C* Bar_Shield; // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay* Overlay_BarsPrefix; // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox* VerticalBox_BarExtensions; // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FTimerHandle VisibiltyTimer; // 0x03B8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool bVisible)> VisibilityChanged; // 0x03C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	float StatusWidgetVisibleDuration; // 0x03D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CurrentHealthPercent; // 0x03D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float CurrentShieldPercent; // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool KeepVisibilityOn; // 0x03DC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8 Pad_3DD[0x3]; // 0x03DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn* FortPawn; // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:

	// Function NPCStatusWidget.NPCStatusWidget_C.BP_HandlePlaylistExtensionWidgetCreated
	// [Event, Protected, BlueprintEvent]
	// NumParams(2) | ParamSize(0x9) | UObject::ProcessInternal(0x76106A4)
	void BP_HandlePlaylistExtensionWidgetCreated(class UUserWidget* Widget, EEUIExtensionSlot SlotType);

	// Function NPCStatusWidget.NPCStatusWidget_C.ChangeWidgetVisibleDuration
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ChangeWidgetVisibleDuration(float StatusWidgetVisibleDuration_0);

	// Function NPCStatusWidget.NPCStatusWidget_C.Construct
	// [BlueprintCosmetic, Event, Public, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void Construct();

	// Function NPCStatusWidget.NPCStatusWidget_C.EventHideStatus
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void EventHideStatus();

	// Function NPCStatusWidget.NPCStatusWidget_C.EventUpdateStatus
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(3) | ParamSize(0x9) | UObject::ProcessInternal(0x76106A4)
	void EventUpdateStatus(float Health, float Shield, bool ShowShield);

	// Function NPCStatusWidget.NPCStatusWidget_C.ExecuteUbergraph_NPCStatusWidget
	// [Final, UbergraphFunction, HasDefaults]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_NPCStatusWidget(int32 EntryPoint);

	// Function NPCStatusWidget.NPCStatusWidget_C.OnPawnFocused
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnPawnFocused();

	// Function NPCStatusWidget.NPCStatusWidget_C.SetKeepVisibilityOn
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void SetKeepVisibilityOn(bool KeepVisibilityOn_0);

	// Function NPCStatusWidget.NPCStatusWidget_C.TryCallEventHideByTimer
	// [BlueprintCallable, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void TryCallEventHideByTimer();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPCStatusWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"NPCStatusWidget_C")
	}
	static class UNPCStatusWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNPCStatusWidget_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UNPCStatusWidget_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
