#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerSurveyOrthogonalIndicator

#include "Basic.hpp"

#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PlayerSurveyOrthogonalIndicator.PlayerSurveyOrthogonalIndicator_C.BndEvt__InputActionWidget_Move_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UPlayerSurveyOrthogonalIndicator_C_BndEvt__InputActionWidget_Move_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature final
{
public:
	UPlayerSurveyOrthogonalIndicator_C_BndEvt__InputActionWidget_Move_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature() {}

	bool bUsingGamepad; // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UPlayerSurveyOrthogonalIndicator_C_BndEvt__InputActionWidget_Move_K2Node_ComponentBoundEvent_0_OnInputMethodChanged__DelegateSignature;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function PlayerSurveyOrthogonalIndicator.PlayerSurveyOrthogonalIndicator_C.ExecuteUbergraph_PlayerSurveyOrthogonalIndicator
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0008) StructUnalignedSize(0x0005) StructAlignment(0x0004)
// 0x0008 (0x0008 - 0x0000)
struct UPlayerSurveyOrthogonalIndicator_C_ExecuteUbergraph_PlayerSurveyOrthogonalIndicator final
{
public:
	UPlayerSurveyOrthogonalIndicator_C_ExecuteUbergraph_PlayerSurveyOrthogonalIndicator() {}

	int32 EntryPoint; // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool K2Node_ComponentBoundEvent_bUsingGamepad; // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UPlayerSurveyOrthogonalIndicator_C_ExecuteUbergraph_PlayerSurveyOrthogonalIndicator;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function PlayerSurveyOrthogonalIndicator.PlayerSurveyOrthogonalIndicator_C.UpdateGamepadControlsVisibility
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UPlayerSurveyOrthogonalIndicator_C_UpdateGamepadControlsVisibility final
{
public:
	UPlayerSurveyOrthogonalIndicator_C_UpdateGamepadControlsVisibility() {}

	EESlateVisibility CallFunc_GetVisibility_ReturnValue; // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UPlayerSurveyOrthogonalIndicator_C_UpdateGamepadControlsVisibility;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
