
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlusMinusButton

#include "Basic.hpp"

#include "PlusMinusButton_classes.hpp"
#include "PlusMinusButton_parameters.hpp"


SDK_NAMESPACE_START

// Function PlusMinusButton.PlusMinusButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UPlusMinusButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlusMinusButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlusMinusButton.PlusMinusButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UPlusMinusButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlusMinusButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlusMinusButton.PlusMinusButton_C.ExecuteUbergraph_PlusMinusButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32 EntryPoint (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlusMinusButton_C::ExecuteUbergraph_PlusMinusButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlusMinusButton_C", "ExecuteUbergraph_PlusMinusButton");

	Params::UPlusMinusButton_C_ExecuteUbergraph_PlusMinusButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlusMinusButton.PlusMinusButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool IsDesignTime (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlusMinusButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlusMinusButton_C", "PreConstruct");

	Params::UPlusMinusButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
