#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuickbarSlotCooldown

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "ItemDisplayStyle_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass QuickbarSlotCooldown.QuickbarSlotCooldown_C
// SuperAlignedSize(0x03B0) SuperUnalignedSize(0x03B0) SuperAlignment(0x0008) SuperLastMemberEnd(0x0359)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x03E0) StructUnalignedSize(0x03D9) StructAlignment(0x0008)
// 0x0030 (0x03E0 - 0x03B0)
class UQuickbarSlotCooldown_C final : public UFortItemCooldownWidget
{
public:
	UQuickbarSlotCooldown_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x03B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage* ImageRadialOpacityLayer; // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage* ImageRectangularOpacityLayer; // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox* ScaleBoxCDCount; // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonWidgetSwitcherLegacy* SwitcherOpacityOverlay; // 0x03D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EItemDisplayStyle ItemDisplayStyle; // 0x03D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:

	// Function QuickbarSlotCooldown.QuickbarSlotCooldown_C.ExecuteUbergraph_QuickbarSlotCooldown
	// [Final, UbergraphFunction]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_QuickbarSlotCooldown(int32 EntryPoint);

	// Function QuickbarSlotCooldown.QuickbarSlotCooldown_C.Initialize
	// [Public, HasOutParams, BlueprintCallable, BlueprintEvent]
	// NumParams(2) | ParamSize(0x18) | UObject::ProcessInternal(0x76106A4)
	void Initialize(EItemDisplayStyle QuickbarItemDisplayStyle, TArray<EEFortItemCooldownType>& DesiredCooldownTypesSupported);

	// Function QuickbarSlotCooldown.QuickbarSlotCooldown_C.OnAmmoRegenerationUpdated
	// [Event, Public, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void OnAmmoRegenerationUpdated(bool bOutAmmoRegenAvailableState);

	// Function QuickbarSlotCooldown.QuickbarSlotCooldown_C.OnCooldownStarted
	// [Event, Public, BlueprintEvent]
	// NumParams(2) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void OnCooldownStarted(EEFortItemCooldownType CooldownType, float CooldownDuration);

	// Function QuickbarSlotCooldown.QuickbarSlotCooldown_C.OnCooldownStopped
	// [Event, Public, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void OnCooldownStopped(EEFortItemCooldownType CooldownType);

	// Function QuickbarSlotCooldown.QuickbarSlotCooldown_C.OnInitialized
	// [BlueprintCosmetic, Event, Public, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnInitialized();

	// Function QuickbarSlotCooldown.QuickbarSlotCooldown_C.Show Countdown
	// [Public, BlueprintCallable, BlueprintEvent]
	// NumParams(1) | ParamSize(0x1) | UObject::ProcessInternal(0x76106A4)
	void Show_Countdown(bool Show);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QuickbarSlotCooldown_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"QuickbarSlotCooldown_C")
	}
	static class UQuickbarSlotCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuickbarSlotCooldown_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UQuickbarSlotCooldown_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
