
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidewaysCodeRuntime

#include "Basic.hpp"

#include "SidewaysCodeRuntime_classes.hpp"
#include "SidewaysCodeRuntime_parameters.hpp"


SDK_NAMESPACE_START

// Function SidewaysCodeRuntime.SidewaysStateComponent.HandleSidewaysStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class ASidewaysPlayspace* NewSidewaysPlayspace (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EESidewaysState OldState (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EESidewaysState NewState (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USidewaysStateComponent::HandleSidewaysStateChanged(class ASidewaysPlayspace* NewSidewaysPlayspace, EESidewaysState OldState, EESidewaysState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidewaysStateComponent", "HandleSidewaysStateChanged");

	Params::USidewaysStateComponent_HandleSidewaysStateChanged Parms{};

	*reinterpret_cast<void**>(&Parms.NewSidewaysPlayspace) = reinterpret_cast<void*>(NewSidewaysPlayspace);
	Parms.OldState = OldState;
	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidewaysCodeRuntime.SidewaysStateComponent.OnRep_SidewaysPlayspace
// (Final, Native, Protected)
// Parameters:
// class ASidewaysPlayspace* NewSidewaysPlayspace (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USidewaysStateComponent::OnRep_SidewaysPlayspace(class ASidewaysPlayspace* NewSidewaysPlayspace)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidewaysStateComponent", "OnRep_SidewaysPlayspace");

	Params::USidewaysStateComponent_OnRep_SidewaysPlayspace Parms{};

	*reinterpret_cast<void**>(&Parms.NewSidewaysPlayspace) = reinterpret_cast<void*>(NewSidewaysPlayspace);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SidewaysCodeRuntime.SidewaysStateComponent.OnRep_SidewaysState
// (Final, Native, Protected)
// Parameters:
// EESidewaysState LastSidewaysState (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USidewaysStateComponent::OnRep_SidewaysState(EESidewaysState LastSidewaysState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidewaysStateComponent", "OnRep_SidewaysState");

	Params::USidewaysStateComponent_OnRep_SidewaysState Parms{};

	Parms.LastSidewaysState = LastSidewaysState;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SidewaysCodeRuntime.SidewaysStateComponent.SetSidewaysState
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)
// Parameters:
// EESidewaysState NewState (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class ASidewaysPlayspace* NewSidewaysPlayspace (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USidewaysStateComponent::SetSidewaysState(EESidewaysState NewState, class ASidewaysPlayspace* NewSidewaysPlayspace)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidewaysStateComponent", "SetSidewaysState");

	Params::USidewaysStateComponent_SetSidewaysState Parms{};

	Parms.NewState = NewState;
	*reinterpret_cast<void**>(&Parms.NewSidewaysPlayspace) = reinterpret_cast<void*>(NewSidewaysPlayspace);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SidewaysCodeRuntime.SidewaysStateComponent.GetSidewaysState
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// EESidewaysState ReturnValue (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EESidewaysState USidewaysStateComponent::GetSidewaysState() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidewaysStateComponent", "GetSidewaysState");

	Params::USidewaysStateComponent_GetSidewaysState Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SidewaysCodeRuntime.SidewaysPlayspace.NotifySizeChanged
// (Final, Native, Public, BlueprintCallable)

void ASidewaysPlayspace::NotifySizeChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidewaysPlayspace", "NotifySizeChanged");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SidewaysCodeRuntime.SidewaysPlayspace.RefreshActorsInSideways
// (Final, Native, Public, BlueprintCallable)

void ASidewaysPlayspace::RefreshActorsInSideways()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidewaysPlayspace", "RefreshActorsInSideways");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SidewaysCodeRuntime.SidewaysLibrary.GetSidewaysStateComponent
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class AActor* Owner (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class USidewaysStateComponent* ReturnValue (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class USidewaysStateComponent* USidewaysLibrary::GetSidewaysStateComponent(const class AActor* Owner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("SidewaysLibrary", "GetSidewaysStateComponent");

	Params::USidewaysLibrary_GetSidewaysStateComponent Parms{};

	*reinterpret_cast<const void**>(&Parms.Owner) = reinterpret_cast<const void*>(Owner);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SidewaysCodeRuntime.SidewaysCheatManager.SetSidewaysState
// (Final, BlueprintAuthorityOnly, Exec, Native, Public)
// Parameters:
// EESidewaysState SidewaysState (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USidewaysCheatManager::SetSidewaysState(EESidewaysState SidewaysState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidewaysCheatManager", "SetSidewaysState");

	Params::USidewaysCheatManager_SetSidewaysState Parms{};

	Parms.SidewaysState = SidewaysState;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
