#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: SideBarProfileSubPanelActions

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass SideBarProfileSubPanelActions.SideBarProfileSubPanelActions_C
// SuperAlignedSize(0x0380) SuperUnalignedSize(0x0380) SuperAlignment(0x0008) SuperLastMemberEnd(0x0338)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0380) StructUnalignedSize(0x0380) StructAlignment(0x0008)
// 0x0000 (0x0380 - 0x0380)
class USideBarProfileSubPanelActions_C final : public UFortSocialProfileActions
{
public:
	USideBarProfileSubPanelActions_C() {}

	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SideBarProfileSubPanelActions_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"SideBarProfileSubPanelActions_C")
	}
	static class USideBarProfileSubPanelActions_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USideBarProfileSubPanelActions_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_USideBarProfileSubPanelActions_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
