
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarSettingsRotator_Narrow

#include "Basic.hpp"

#include "SidebarSettingsRotator_Narrow_classes.hpp"
#include "SidebarSettingsRotator_Narrow_parameters.hpp"


SDK_NAMESPACE_START

// Function SidebarSettingsRotator_Narrow.SidebarSettingsRotator_Narrow_C.OnUnHover Animation
// (BlueprintCallable, BlueprintEvent)

void USidebarSettingsRotator_Narrow_C::OnUnHover_Animation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarSettingsRotator_Narrow_C", "OnUnHover Animation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SidebarSettingsRotator_Narrow.SidebarSettingsRotator_Narrow_C.OnHover Animation
// (BlueprintCallable, BlueprintEvent)

void USidebarSettingsRotator_Narrow_C::OnHover_Animation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarSettingsRotator_Narrow_C", "OnHover Animation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SidebarSettingsRotator_Narrow.SidebarSettingsRotator_Narrow_C.ExecuteUbergraph_SidebarSettingsRotator_Narrow
// (Final, UbergraphFunction)
// Parameters:
// int32 EntryPoint (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarSettingsRotator_Narrow_C::ExecuteUbergraph_SidebarSettingsRotator_Narrow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarSettingsRotator_Narrow_C", "ExecuteUbergraph_SidebarSettingsRotator_Narrow");

	Params::USidebarSettingsRotator_Narrow_C_ExecuteUbergraph_SidebarSettingsRotator_Narrow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarSettingsRotator_Narrow.SidebarSettingsRotator_Narrow_C.BP_OnOptionsPopulated
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32 Count_BP_OnOptionsPopulated (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarSettingsRotator_Narrow_C::BP_OnOptionsPopulated(int32 Count_BP_OnOptionsPopulated)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarSettingsRotator_Narrow_C", "BP_OnOptionsPopulated");

	Params::USidebarSettingsRotator_Narrow_C_BP_OnOptionsPopulated Parms{};

	Parms.Count_BP_OnOptionsPopulated = Count_BP_OnOptionsPopulated;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarSettingsRotator_Narrow.SidebarSettingsRotator_Narrow_C.BP_OnOptionSelected
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32 Index_BP_OnOptionSelected (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarSettingsRotator_Narrow_C::BP_OnOptionSelected(int32 Index_BP_OnOptionSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarSettingsRotator_Narrow_C", "BP_OnOptionSelected");

	Params::USidebarSettingsRotator_Narrow_C_BP_OnOptionSelected Parms{};

	Parms.Index_BP_OnOptionSelected = Index_BP_OnOptionSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SidebarSettingsRotator_Narrow.SidebarSettingsRotator_Narrow_C.BP_OnDefaultOptionSpecified
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32 DefaultOptionIndex_BP_OnDefaultOptionSpecified (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USidebarSettingsRotator_Narrow_C::BP_OnDefaultOptionSpecified(int32 DefaultOptionIndex_BP_OnDefaultOptionSpecified)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SidebarSettingsRotator_Narrow_C", "BP_OnDefaultOptionSpecified");

	Params::USidebarSettingsRotator_Narrow_C_BP_OnDefaultOptionSpecified Parms{};

	Parms.DefaultOptionIndex_BP_OnDefaultOptionSpecified = DefaultOptionIndex_BP_OnDefaultOptionSpecified;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
