#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: SignInWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass SignInWidget.SignInWidget_C
// SuperAlignedSize(0x05A0) SuperUnalignedSize(0x05A0) SuperAlignment(0x0008) SuperLastMemberEnd(0x05A0)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x05B8) StructUnalignedSize(0x05B8) StructAlignment(0x0008)
// 0x0018 (0x05B8 - 0x05A0)
class USignInWidget_C final : public UFortSignInWidget
{
public:
	USignInWidget_C() {}

	class UNamedSlot* ButtonSlot; // 0x05A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonLazyImage* None; // 0x05A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox* ContentBox; // 0x05B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SignInWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"SignInWidget_C")
	}
	static class USignInWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USignInWidget_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_USignInWidget_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
