
/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: Task_SetBlackboardBoolValues

#include "Basic.hpp"

#include "Task_SetBlackboardBoolValues_classes.hpp"
#include "Task_SetBlackboardBoolValues_parameters.hpp"


SDK_NAMESPACE_START

// Function Task_SetBlackboardBoolValues.Task_SetBlackboardBoolValues_C.ExecuteUbergraph_Task_SetBlackboardBoolValues
// (Final, UbergraphFunction)
// Parameters:
// int32 EntryPoint (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTask_SetBlackboardBoolValues_C::ExecuteUbergraph_Task_SetBlackboardBoolValues(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_SetBlackboardBoolValues_C", "ExecuteUbergraph_Task_SetBlackboardBoolValues");

	Params::UTask_SetBlackboardBoolValues_C_ExecuteUbergraph_Task_SetBlackboardBoolValues Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Task_SetBlackboardBoolValues.Task_SetBlackboardBoolValues_C.ReceiveExecute
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor* OwnerActor (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTask_SetBlackboardBoolValues_C::ReceiveExecute(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_SetBlackboardBoolValues_C", "ReceiveExecute");

	Params::UTask_SetBlackboardBoolValues_C_ReceiveExecute Parms{};

	*reinterpret_cast<void**>(&Parms.OwnerActor) = reinterpret_cast<void*>(OwnerActor);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
