#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: TeamMemberPedestal_FeatInfo

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass TeamMemberPedestal_FeatInfo.TeamMemberPedestal_FeatInfo_C
// SuperAlignedSize(0x1070) SuperUnalignedSize(0x1070) SuperAlignment(0x0010) SuperLastMemberEnd(0x1068)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x1080) StructUnalignedSize(0x1080) StructAlignment(0x0010)
// 0x0010 (0x1080 - 0x1070)
class UTeamMemberPedestal_FeatInfo_C final : public UFortTeamMemberPedestalFeatInfo
{
public:
	UTeamMemberPedestal_FeatInfo_C() {}

	struct FPointerToUberGraphFrame UberGraphFrame; // 0x1070(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation* FeatInfoSet; // 0x1078(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:

	// Function TeamMemberPedestal_FeatInfo.TeamMemberPedestal_FeatInfo_C.OnFeatDefinitionSet
	// [Event, Protected, BlueprintEvent]
	// NumParams(0) | ParamSize(0x0) | UObject::ProcessInternal(0x76106A4)
	void OnFeatDefinitionSet();

	// Function TeamMemberPedestal_FeatInfo.TeamMemberPedestal_FeatInfo_C.OnAnimationFinished
	// [BlueprintCosmetic, Event, Protected, BlueprintEvent]
	// NumParams(1) | ParamSize(0x8) | UObject::ProcessInternal(0x76106A4)
	void OnAnimationFinished(const class UWidgetAnimation* Animation_OnAnimationFinished);

	// Function TeamMemberPedestal_FeatInfo.TeamMemberPedestal_FeatInfo_C.ExecuteUbergraph_TeamMemberPedestal_FeatInfo
	// [Final, UbergraphFunction]
	// NumParams(1) | ParamSize(0x4) | UObject::ProcessInternal(0x76106A4)
	void ExecuteUbergraph_TeamMemberPedestal_FeatInfo(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TeamMemberPedestal_FeatInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"TeamMemberPedestal_FeatInfo_C")
	}
	static class UTeamMemberPedestal_FeatInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTeamMemberPedestal_FeatInfo_C>();
	}
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UTeamMemberPedestal_FeatInfo_C;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_NAMESPACE_END
