#pragma once

/*
* SDK generated by MobileDumper-7 & Dumper-7
*
* https://github.com/MJx0/MobileDumper-7
* https://github.com/Encryqed/Dumper-7
*/

// Package: ThrowingToyRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ThrowingToyRuntime_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function ThrowingToyRuntime.ThrowingToyTrackerComponent.AddThrowingToy
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UThrowingToyTrackerComponent_AddThrowingToy final
{
public:
	UThrowingToyTrackerComponent_AddThrowingToy() {}

	class AActor* ThrowingToyActor; // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGuid WorldItemGuid; // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UThrowingToyTrackerComponent_AddThrowingToy;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function ThrowingToyRuntime.ThrowingToyTrackerComponent.GetAndReleaseThrowingToy
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UThrowingToyTrackerComponent_GetAndReleaseThrowingToy final
{
public:
	UThrowingToyTrackerComponent_GetAndReleaseThrowingToy() {}

	struct FGuid WorldItemGuid; // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor* ReturnValue; // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UThrowingToyTrackerComponent_GetAndReleaseThrowingToy;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function ThrowingToyRuntime.ThrowingToyTrackerComponent.GetRecentThrowingToyItemRemovedReason
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UThrowingToyTrackerComponent_GetRecentThrowingToyItemRemovedReason final
{
public:
	UThrowingToyTrackerComponent_GetRecentThrowingToyItemRemovedReason() {}

	EEThrowingToyItemRemovedReason ReturnValue; // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UThrowingToyTrackerComponent_GetRecentThrowingToyItemRemovedReason;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function ThrowingToyRuntime.ThrowingToyTrackerComponent.GetThrowingToy
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0018) StructUnalignedSize(0x0018) StructAlignment(0x0008)
// 0x0018 (0x0018 - 0x0000)
struct UThrowingToyTrackerComponent_GetThrowingToy final
{
public:
	UThrowingToyTrackerComponent_GetThrowingToy() {}

	struct FGuid WorldItemGuid; // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor* ReturnValue; // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UThrowingToyTrackerComponent_GetThrowingToy;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

// Function ThrowingToyRuntime.ThrowingToyTrackerComponent.SetRecentThrowingToyItemRemovedReason
// SuperAlignedSize(0x0000) SuperUnalignedSize(0x0000) SuperAlignment(0x0000) SuperLastMemberEnd(0x0000)
// bHasReusedTrailingPadding(false) bIsReusingTrailingPaddingFromSuper(false)
// StructAlignedSize(0x0001) StructUnalignedSize(0x0001) StructAlignment(0x0001)
// 0x0001 (0x0001 - 0x0000)
struct UThrowingToyTrackerComponent_SetRecentThrowingToyItemRemovedReason final
{
public:
	UThrowingToyTrackerComponent_SetRecentThrowingToyItemRemovedReason() {}

	EEThrowingToyItemRemovedReason RemovedReason; // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#endif
DUMPER7_ASSERTS_UThrowingToyTrackerComponent_SetRecentThrowingToyItemRemovedReason;
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
